-- V25: Update certificate_type constraint to match new CertificateType enum
-- The CertificateType enum has been expanded to include many more certificate types
-- This migration removes the restrictive check constraint to allow all new certificate types

-- Drop the restrictive check constraint that only allows 3 old certificate types
ALTER TABLE customers DROP CONSTRAINT IF EXISTS check_certificate_type;

-- Update the column comment to reflect the new certificate types
COMMENT ON COLUMN customers.certificate_type IS 'Certificate type from CertificateType enum: Q1_COMMAND, Q2_MOBILE_CRANE, Q2_BRIDGE_CRANE, Q2_GANTRY_CRANE, Q2_TOWER_CRANE, Q2_HOIST, N1_FORKLIFT, N2_SIGHTSEEING_CAR, G1_INDUSTRIAL_BOILER, G3_BOILER_WATER_TREATMENT, R1_QUICK_OPEN_PRESSURE_VESSEL, R2_MOBILE_PRESSURE_VESSEL, P_GAS_FILLING, A_SPECIAL_EQUIPMENT_SAFETY, T_ELEVATOR_OPERATION, CONSTRUCTION_ELECTRICIAN, CONSTRUCTION_WELDER, CONSTRUCTION_SCAFFOLDER, CONSTRUCTION_LIFTING_EQUIPMENT, CONSTRUCTION_SIGNALMAN, CONSTRUCTION_MATERIAL_HOIST_DRIVER, CONSTRUCTION_GONDOLA_INSTALLER, LOW_VOLTAGE_ELECTRICIAN, WELDING_THERMAL_CUTTING, HIGH_VOLTAGE_ELECTRICIAN, HIGH_ALTITUDE_INSTALLATION, HIGH_ALTITUDE_SCAFFOLDING, REFRIGERATION_AIR_CONDITIONING, COAL_MINE_SAFETY, METAL_NONMETAL_MINE_SAFETY, OIL_GAS_SAFETY, HAZARDOUS_CHEMICALS_SAFETY, METALLURGY_SAFETY, FIREWORKS_SAFETY, OTHERS';
