'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh-CN';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  'en': {
    // Common
    'common.close': 'Close',


    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.language.en': 'English',
    'settings.language.zh-CN': '简体中文',

    // Customer Management
    'customer.name': 'Name',
    'customer.currentStatus': 'Current Status',
    'customer.salesPerson': 'Business Manager',

    // Status
    'status.new': 'New',
    'status.notified': 'Notified',
    'status.aborted': 'Aborted',
    'status.submitted': 'Submitted',
    'status.certified': 'Certified',
    'status.certifiedElsewhere': 'Renewed Elsewhere',

    // Approval Status
    'approvalStatus.pending': 'Pending',
    'approvalStatus.approved': 'Approved',
    'approvalStatus.rejected': 'Rejected',

    // Dashboard

    // Auth
    'auth.logout': 'Logout',
    'auth.phone': 'Phone',
    'auth.password': 'Password',
    'auth.registerFailed': 'Registration failed',
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInToAccount': 'Sign in to your sales account',
    'auth.phoneNumber': 'Phone Number',
    'auth.enterPhone': 'Enter your phone number',
    'auth.enterPassword': 'Enter your password',
    'auth.signingIn': 'Signing In...',
    'auth.signIn': 'Sign In',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.createAccount': 'Create Account',
    'auth.registrationComplete': 'Registration Complete!',
    'auth.customerTracker': 'Customer Tracker',

    // Change Password
    'password.title': 'Change Password',
    'password.forcedTitle': 'Change Your Password',
    'password.forcedChangeMessage': 'For security reasons, you must change your password before continuing.',
    'password.label.currentPassword': 'Current Password',
    'password.label.newPassword': 'New Password',
    'password.label.confirmPassword': 'Confirm New Password',
    'password.placeholder.currentPassword': 'Enter your current password',
    'password.placeholder.newPassword': 'Enter your new password',
    'password.placeholder.confirmPassword': 'Confirm your new password',
    'password.button.change': 'Change Password',
    'password.button.continue': 'Continue',
    'password.button.changing': 'Changing...',
    'password.button.cancel': 'Cancel',
    'password.requirements.title': 'Password Requirements',
    'password.requirements.length': 'At least 6 characters',
    'password.requirements.different': 'Must be different from current password',
    'password.requirements.met': 'Password meets requirements',
    'password.success.changed': 'Password changed successfully',
    'password.error.currentPasswordRequired': 'Current password is required',
    'password.error.newPasswordRequired': 'New password is required',
    'password.error.confirmPasswordRequired': 'Please confirm your new password',
    'password.error.passwordTooShort': 'Password must be at least 6 characters',
    'password.error.passwordsDoNotMatch': 'Passwords do not match',
    'password.error.failed': 'Failed to change password',

    // Error messages
    'error.phonePasswordRequired': 'Phone and password are required',
    'error.incorrectCredentials': 'Incorrect phone number or password. Please check your credentials and try again.',
    'error.networkError': 'Unable to connect to the server. Please check your internet connection and try again.',
    'error.unexpectedError': 'An unexpected error occurred. Please try again.',
    'error.loginFailed': 'Login Failed',
    'error.invalidCredentials': 'Invalid Credentials',
    'error.accountPending': 'Account Pending Approval',
    'error.accountDenied': 'Account Access Denied',
    'error.accountDisabled': 'Your account has been disabled by an administrator. Please contact support for assistance.',
    'error.connectionError': 'Connection Error',
    'error.dismissMessage': 'Dismiss error message',
    'error.phoneAlreadyExists': 'Phone number already exists',
    'error.duplicateCustomerCertificate': 'This phone number already has a certificate of this type. Please edit the existing customer or choose a different certificate type.',
    'error.invalidToken': 'Invalid or expired token',
    'error.invalidResponse': 'Invalid response from server',
    'error.updateFailed': 'Update Failed',
    'error.sessionConflict': 'You have been logged out because you logged in on another device.',
    'error.sessionConflictTitle': 'Logged Out Due to New Login',

    // Error help messages
    'error.tips': 'Tips:',
    'error.whatHappened': 'What happened:',
    'error.sessionConflictExplanation': 'Your account was used to sign in on a different device, which automatically signed you out from this session.',
    'error.sessionCanRelogin': 'You can sign in again to continue using this device.',
    'error.checkPhoneFormat': 'Double-check your phone number format',
    'error.ensurePassword': 'Ensure your password is correct',
    'error.capsLock': 'Make sure Caps Lock is not enabled',
    'error.whatToDo': 'What to do next:',
    'error.waitApproval': 'Please wait for admin approval',
    'error.contactAdmin': 'Contact admin if you need immediate access',
    'error.tryAgainLater': 'Try logging in again later',
    'error.needHelp': 'Need help?',
    'error.contactSystemAdmin': 'Contact your system administrator to discuss your account status and request access.',
    'error.trySteps': 'Try these steps:',
    'error.checkConnection': 'Check your internet connection',
    'error.refreshPage': 'Refresh the page and try again',
    'error.contactSupport': 'Contact support if the problem persists',

    // Navigation
    'nav.adminDashboard': 'Admin Dashboard',
    'nav.dashboard': 'Reports',
    'nav.customers': 'Customers',
    'nav.batchImport': 'Batch Import',
    'nav.settings': 'Settings',
    'nav.userManagement': 'User Management',
    'nav.refresh': 'Refresh',
    'nav.refreshing': 'Refreshing...',

    // Landing Page
    'landing.welcome': 'Welcome',
    'landing.welcomeMessage': 'Welcome to Customer Tracker. Here\'s what you can do today.',
    'landing.quickAccess': 'Quick Access',
    'landing.availableActions': 'Available Actions',
    'landing.yourRole': 'Your Role',
    'landing.accountStatus': 'Account Active',
    'landing.systemStatus': 'System Status',
    'landing.online': 'Online',
    'landing.ready': 'Ready',
    'landing.quickActions': 'Quick Actions',
    'landing.manageCustomers': 'Manage Customers',
    'landing.manageCustomersDesc': 'View, add, edit, and manage customer information',
    'landing.viewDashboardDesc': 'View analytics, reports, and performance metrics',
    'landing.batchImportDesc': 'Import or export customer data in bulk',
    'landing.userManagementDesc': 'Manage user approvals and permissions',
    'landing.gettingStarted': 'Getting Started',
    'landing.tip1': 'Click on "Manage Customers" to view and manage your customer list',
    'landing.tip2': 'Use the Reports to track performance and view statistics',
    'landing.tip3': 'Access Settings from the bottom of the sidebar to manage your account',

    // General

    // App
    'app.customerTracker': 'Customer Tracker',
    'app.admin': '(Admin)',

    // Customer List
    'customers.addCustomer': 'Add Customer',
    'customers.searchPlaceholder': 'Search by name or phone...',
    'customers.search': 'Search',
    'customers.all': 'All',
    'customers.searchStatus': 'Status',
    'customers.startDate': 'Start Date',
    'customers.endDate': 'End Date',
    'customers.clear': 'Clear',
    'customers.errorLoading': 'Error loading customers',
    'customers.tryAgain': 'Try Again',
    'customers.loadingCustomers': 'Loading customers...',
    'customers.noCustomersFound': 'No customers found',
    'customers.adjustSearch': 'Try adjusting your search terms',
    'customers.getStartedFirst': 'Get started by adding your first customer',
    'customers.clearSearch': 'Clear Search',
    'customers.of': 'of',
    'customers.showing': 'Showing',
    'customers.to': 'to',
    'customers.customers': 'customers',
    'customers.show': 'Show:',
    'customers.perPage': 'per page',
    'customers.name': 'Name',
    'customers.phone': 'Phone',
    'customers.cancel': 'Cancel',
    'customers.confirm': 'Confirm',
    'customers.close': 'Close',
    'customers.ok': 'OK',
    'customers.detail.customer': 'Customer',

    // Customer Form
    'customers.form.createCustomer': 'Create Customer',
    'customers.form.name': 'Full Name',
    'customers.form.phone': 'Phone Number',
    'customers.form.certificateIssuer': 'Certificate Issuer',
    'customers.form.businessReq': 'Comments',
    'customers.form.certificateType': 'Certificate Type',
    'customers.form.age': 'Age',
    'customers.form.education': 'Education Level',
    'customers.form.gender': 'Gender',
    'customers.form.gender.male': 'Male',
    'customers.form.gender.female': 'Female',
    'customers.form.gender.other': 'Other',
    'customers.form.gender.select': 'Select gender',
    'customers.form.address': 'Address',
    'customers.form.salesPerson': 'Added By',
    'customers.form.salesPerson.unknown': 'Unknown',
    'customers.form.salesPerson.you': 'You',
    'customers.form.customerAgent': 'Business Manager',
    'customers.form.customerAgent.placeholder': 'Enter agent name',
    'customers.form.customerType': 'Customer Type',
    'customers.detail.statusManagement': 'Status Management',
    'customers.detail.updateStatus': 'Update Status',
    'customers.detail.updating': 'Updating...',
    'detail.initialStatus': 'Initial status:',
    'customers.detail.businessComplete': 'Business process is complete - no further transitions allowed',
    'customers.detail.loadingTransitions': 'Loading available transitions...',
    'customers.detail.initialCreation': 'Initial customer creation',
    'customers.detail.statusReason': 'Enter reason for status change...',
    'customers.detail.reasonOptional': 'Reason (Optional)',
    'customers.detail.newStatus': 'New Status',
    'customers.detail.noTransitionsAvailable': 'No status transitions available',
    'customers.detail.selectEducationLevel': 'Select education level',
    'customers.detail.notSpecified': 'Not specified',

    // Education Levels
    'education.elementary': 'Elementary School',
    'education.middleSchool': 'Middle School',
    'education.highSchool': 'High School',
    'education.secondaryVocational': 'Secondary Vocational School',
    'education.associate': 'Associate Degree',
    'education.bachelor': 'Bachelor\'s Degree',
    'education.master': 'Master\'s Degree',
    'education.doctorate': 'Doctorate/PhD',
    'education.professional': 'Professional Degree',
    'education.certificate': 'Certificate/Diploma',
    'education.other': 'Other',
    // Customer Type
    'customerType.newCustomer': 'New Customer',
    'customerType.renewCustomer': 'Renew Customer',
    // Crane & Machinery Types (起重机械)
    'certificateType.q1Command': 'Q1 Crane Commander',
    'certificateType.q2MobileCrane': 'Q2 Mobile Crane',
    'certificateType.q2BridgeCrane': 'Q2 Bridge Crane',
    'certificateType.q2GantryCrane': 'Q2 Gantry Crane',
    'certificateType.q2TowerCrane': 'Q2 Tower Crane',
    'certificateType.q2Hoist': 'Q2 Hoist/Lift',

    // Forklift & Industrial Vehicles
    'certificateType.n1Forklift': 'N1 Forklift',
    'certificateType.n2SightseeingCar': 'N2 Sightseeing Car',

    // Boiler & Pressure Vessels (锅炉压力容器)
    'certificateType.g1IndustrialBoiler': 'G1 Industrial Boiler',
    'certificateType.g3BoilerWaterTreatment': 'G3 Boiler Water Treatment',
    'certificateType.r1QuickOpenPressureVessel': 'R1 Quick-Open Pressure Vessel',
    'certificateType.r2MobilePressureVessel': 'R2 Mobile Pressure Vessel',
    'certificateType.pGasFilling': 'P Gas Cylinder Filling',

    // Safety Management
    'certificateType.aSpecialEquipmentSafety': 'A Special Equipment Safety Management',

    // Elevator Operations
    'certificateType.tElevatorOperation': 'T Elevator Operation',

    // Construction Trades (建筑施工)
    'certificateType.constructionElectrician': 'Construction Electrician',
    'certificateType.constructionWelder': 'Construction Welder',
    'certificateType.constructionScaffolder': 'Construction Scaffolder',
    'certificateType.constructionLiftingEquipment': 'Construction Lifting Equipment Operation',
    'certificateType.constructionSignalman': 'Construction Rigger/Signalman',
    'certificateType.constructionMaterialHoistDriver': 'Construction Material Hoist Driver',
    'certificateType.constructionGondolaInstaller': 'Construction Gondola Installer',

    // Electrical Operations (电工作业)
    'certificateType.lowVoltageElectrician': 'Low Voltage Electrician',
    'certificateType.weldingThermalCutting': 'Welding & Thermal Cutting',
    'certificateType.highVoltageElectrician': 'High Voltage Electrician',

    // High-Altitude Work (高处作业)
    'certificateType.highAltitudeInstallation': 'High Altitude Installation/Maintenance/Dismantling',
    'certificateType.highAltitudeScaffolding': 'High Altitude Scaffolding',

    // Specialized Operations
    'certificateType.refrigerationAirConditioning': 'Refrigeration & Air Conditioning',

    // Mining & Industry Safety (矿山安全作业)
    'certificateType.coalMineSafety': 'Coal Mine Safety Operation',
    'certificateType.metalNonmetalMineSafety': 'Metal/Non-Metal Mine Safety Operation',

    // Petroleum & Chemical Safety (石油化工安全)
    'certificateType.oilGasSafety': 'Oil & Natural Gas Safety Operation',
    'certificateType.hazardousChemicalsSafety': 'Hazardous Chemicals Safety Operation',
    'certificateType.metallurgySafety': 'Metallurgy (Non-Ferrous) Production Safety Operation',
    'certificateType.fireworksSafety': 'Fireworks Safety Operation',

    // Other types for backward compatibility
    'certificateType.others': 'Others',
    'customers.form.selectCertificateType': 'Select certificate type',
    'certificateIssuer.marketSupervisionAdministration': 'Market Supervision Administration',
    'certificateIssuer.housingConstructionBureau': 'Housing and Construction Bureau',
    'certificateIssuer.emergencyManagementDepartment': 'Emergency Management Department',
    'certificateIssuer.other': 'Other',
    'approvals.showing': 'Showing',
    'approvals.to': 'to',
    'approvals.of': 'of',
    'approvals.users': 'users',
    'approvals.show': 'Show:',
    'approvals.perPage': 'per page',
    'approvals.noUsersFound': 'No users found',
    'approvals.noUsersFoundMatching': 'No users found matching',
    'approvals.noUsersWithStatus': 'No users with status',
    'approvals.approveUser': 'Approve User',
    'approvals.rejectUser': 'Reject User',
    'approvals.resetToPending': 'Reset to Pending',
    'approvals.firstPage': 'First page',
    'approvals.previousPage': 'Previous page',
    'approvals.nextPage': 'Next page',
    'approvals.lastPage': 'Last page',
    'approvals.approveTitle': 'Approve User Registration',
    'approvals.approveDescription': 'Approve registration for',
    'approvals.approveButton': 'Approve User',
    'approvals.approveReason': 'Approval reason (optional)',
    'approvals.approvePlaceholder': 'e.g., Application looks good, verified identity...',
    'approvals.rejectTitle': 'Reject User Registration',
    'approvals.rejectDescription': 'Reject registration for',
    'approvals.rejectButton': 'Reject User',
    'approvals.rejectReason': 'Rejection reason *',
    'approvals.rejectPlaceholder': 'e.g., Incomplete application, verification failed...',
    'approvals.resetTitle': 'Reset User Status',
    'approvals.resetDescription': 'Reset',
    'approvals.resetDescription2': 'status back to pending?',
    'approvals.resetButton': 'Reset Status',
    'approvals.resetReason': 'Reset reason (optional)',
    'approvals.resetPlaceholder': 'e.g., Need to review application again...',
    'approvals.processing': 'Processing...',
    'dashboard.sales.myConversionRate': 'My Conversion Rate',
    'dashboard.sales.conversionProgress': 'Conversion Progress',
    'dashboard.sales.conversionRate': 'conversion rate',
    'dashboard.sales.keyMetrics': 'Key Metrics',
    'dashboard.sales.newCustomers': 'New Customers',
    'dashboard.sales.conversions': 'Deals',
    'dashboard.sales.rate': 'rate',
    'dashboard.sales.quickActions': 'Quick Actions',
    'dashboard.sales.viewAllCustomers': 'View All Customers',
    'dashboard.sales.followUpCalls': 'Follow Up Calls',
    'dashboard.sales.pendingOrders': 'Pending Orders',
    'customers.form.idCard': 'ID Card',
    'customers.form.idCardPlaceholder': 'Enter ID card number',
    'customers.form.idCardHelp': 'Only digits and English letters are allowed',
    'customers.form.noIdCard': 'No ID card',
    'customers.form.certifiedAt': 'Certified Date',
    'customers.form.certifiedAt.placeholder': 'Select certification date',
    'customers.form.creating': 'Creating...',
    'customers.form.create': 'Create Customer',
    'customers.form.updating': 'Updating...',
    'customers.form.update': 'Update Customer',
    'customers.form.cancel': 'Cancel',

    // Batch Import
    'batchImport.uploadExcel': 'Upload Excel File',
    'batchImport.selectFile': 'Select Excel File (.xlsx)',
    'batchImport.remove': 'Remove',
    'batchImport.uploading': 'Uploading...',
    'batchImport.uploadFailed': 'Failed to upload file. Please try again.',
    'batchImport.status': 'Status',
    'batchImport.cancelClear': 'Cancel & Clear',
    'batchImport.confirmImport': 'Confirm Import',
    'batchImport.importing': 'Importing...',
    'batchImport.cancelling': 'Cancelling...',
    'batchImport.pleaseWait': 'Please wait...',
    'batchImport.newCustomersImported': 'New Customers Imported',
    'batchImport.customersUpdated': 'Customers Updated',
    'batchImport.skipped': 'Skipped (Duplicates/Invalid)',
    'batchImport.newToImport': 'New to Import',
    'batchImport.toUpdate': 'To Update',
    'batchImport.duplicates': 'Duplicates',
    'batchImport.invalid': 'Invalid',
    'batchImport.uploadNow': 'Upload Now',
    'batchImport.permissionDenied': 'Permission Denied',
    'batchImport.noPermissionMessage': 'You don&apos;t have permission to access batch import functionality.',
    'batchImport.status.valid': 'Valid',
    'batchImport.status.update': 'Update',
    'batchImport.status.duplicate': 'Duplicate',
    'batchImport.status.invalid': 'Invalid',
    'batchImport.validationMessage': 'Validation Message',
    'batchImport.confirmNewFileTitle': 'Unconfirmed Data',
    'batchImport.confirmNewFileMessage': 'There\'s still data not confirmed. Do you still want to select another file?',
    'batchImport.confirmNewFileYes': 'Yes, clear and select new file',
    'batchImport.confirmNewFileNo': 'No, keep current data',
    'batchImport.updateFilterInfo': 'Fields displayed in red text will be updated in existing customer records.',

    // Customer Detail
    'customers.detail.customerDetails': 'Customer Details',
    'customers.detail.edit': 'Edit',
    'customers.detail.back': 'Back to List',
    'customers.detail.loading': 'Loading customer details...',
    'customers.detail.notFound': 'Customer not found',
    'customers.detail.failedLoad': 'Failed to load customer details',
    'customers.detail.statusTransitionFailed': 'Status Transition Failed',
    'customers.updateSuccess': 'Customer updated successfully',

    // Registration
    'register.createAccount': 'Create Account',
    'register.joinPlatform': 'Join our customer management platform',
    'register.allFieldsRequired': 'All fields are required',
    'register.passwordsDontMatch': 'Passwords do not match',
    'register.passwordTooShort': 'Password must be at least 6 characters long',
    'register.confirmPassword': 'Confirm Password',
    'register.enterConfirmPassword': 'Confirm your password',
    'register.creating': 'Creating Account...',
    'register.alreadyHaveAccount': 'Already have an account?',
    'register.signIn': 'Sign In',
    'register.createPassword': 'Create a password',
    'register.minimumChars': 'Minimum 6 characters',
    'register.selectRole': 'Select Role',
    'register.role': 'Role',

    // Roles
    'role.admin': 'Admin',
    'role.officer': 'Officer',
    'role.customerAgent': 'Business Manager',

    // Delete Requests
    'deleteRequests.title': 'Customer Delete Requests',
    'deleteRequests.loadingRequests': 'Loading delete requests...',
    'deleteRequests.requestedBy': 'Requested by',
    'deleteRequests.reason': 'Reason',
    'deleteRequests.requestedAt': 'Requested',
    'deleteRequests.approve': 'Approve',
    'deleteRequests.reject': 'Reject',
    'deleteRequests.requestDeletion': 'Request Deletion',
    'deleteRequests.requestDeleteSuccess': 'Delete request submitted successfully',
    'deleteRequests.requestDeleteError': 'Failed to submit delete request',
    'deleteRequests.pendingRequestExists': 'A pending delete request already exists for this customer',
    'deleteRequests.requestSubmitted': 'Request Submitted',
    'deleteRequests.reasonRequired': 'Reason is required',
    'deleteRequests.reasonPlaceholder': 'Please provide a reason for the deletion request...',
    'deleteRequests.submitting': 'Submitting...',
    'deleteRequests.pending': 'Pending',
    'deleteRequests.approved': 'Approved',
    'deleteRequests.rejected': 'Rejected',
    'deleteRequests.rejectionReason': 'Rejection Reason',
    'deleteRequests.searchPlaceholder': 'Search by name, phone, or requester',
    'deleteRequests.noRequestsFound': 'No delete requests found',
    'deleteRequests.noRequestsMatching': 'No delete requests matching',
    'deleteRequests.noPendingRequests': 'No pending delete requests',
    'deleteRequests.noApprovedRequests': 'No approved delete requests',
    'deleteRequests.noRejectedRequests': 'No rejected delete requests',
    'deleteRequests.approveFailed': 'Failed to approve request',
    'deleteRequests.rejectFailed': 'Failed to reject request',
    'deleteRequests.rejectRequest': 'Reject Delete Request',
    'deleteRequests.rejectionReasonRequired': 'Rejection reason is required',
    'deleteRequests.rejectionReasonPlaceholder': 'Please provide a reason for rejection...',
    'deleteRequests.rejectionReasonHelp': 'This reason will be visible to the requester',
    'deleteRequests.rejecting': 'Rejecting...',
    'deleteRequests.approveRequest': 'Approve Delete Request',
    'deleteRequests.approvalReason': 'Approval Reason',
    'deleteRequests.approvalReasonPlaceholder': 'Optional: Add a comment or reason for approval...',
    'deleteRequests.approvalReasonHelp': 'This comment will be visible to the requester',
    'deleteRequests.approving': 'Approving...',
    'deleteRequests.optional': 'optional',
    'deleteRequests.requests': 'requests',

    // Permission Errors
    'error.permissionDenied': 'Permission Denied',
    'error.onlyAdminAndAgentCanAdd': 'Only Admins and Officers can add customers',

    // Registration Success
    'register.success.title': 'Registration Successful!',
    'register.success.message': 'Your account has been created and is pending approval.',
    'register.success.adminReview': 'An administrator will review your request shortly.',
    'register.success.notification': 'You will be notified once your account is approved.',
    'register.success.backToLogin': 'Back to Login',

    // Validation messages
    'validation.certificateTypeRequired': 'Certificate type is required',
    'validation.idCardRequired': 'ID card is required',

    // Common actions

    // Dashboard - Admin
    'dashboard.admin.backToCustomers': 'Back to Customers',

    // Dashboard - Sales

    // Dashboard - Metrics
    'dashboard.metrics.totalCustomers': 'Total Certified Customers',
    'dashboard.metrics.newCustomers': 'New Certifications',
    'dashboard.metrics.unsettled': 'Unsettled',
    'dashboard.metrics.conversionRate': 'Conversion Rate',
    'dashboard.metrics.newCustomers30d': 'Certified this month',
    'dashboard.metrics.fromLastPeriod': 'from last period',
    'dashboard.metrics.recentActivity': 'Customers not yet certified',
    'dashboard.metrics.loadingDashboard': 'Loading reports...',
    'dashboard.metrics.errorLoadingDashboard': 'Error loading reports',
    'dashboard.metrics.viewCustomers': 'View Customers',
    'dashboard.metrics.myCustomers': 'My Customers',

    // Dashboard - Charts
    'dashboard.charts.statusDistribution': 'Not Certified Customer Status Distribution',
    'dashboard.charts.trends': 'Customer Certification Trends',
    'dashboard.charts.noData': 'No data available',
    'dashboard.charts.error': 'Error',
    'dashboard.charts.errorLoading': 'Error loading chart',
    'dashboard.charts.refresh': 'Refresh Reports',
    'dashboard.charts.total': 'total',
    'dashboard.charts.totalLabel': 'Total',
    'dashboard.charts.totalCustomers': 'Total',
    'dashboard.charts.customers': 'customers',
    'dashboard.charts.ofTotal': 'of total',
    'dashboard.charts.quickStats': 'Quick Stats',
    'dashboard.charts.highestCount': 'Highest Count',
    'dashboard.charts.statusTypes': 'Status Types',
    'dashboard.charts.dataWillAppear': 'Customer status data will appear here when available',
    'dashboard.charts.newCertifications': 'Certified Monthly',
    'dashboard.charts.conversionRate': 'Conversion Rate (%)',
    'dashboard.charts.leaderboard': 'Customer Agent Leaderboard',
    'dashboard.charts.certificateTypeTrends': 'Certificate Type Trends',
    'dashboard.charts.selectCertificateTypes': 'Select Certificate Types',
    'dashboard.charts.allCertificateTypes': 'All Certificate Types',
    'dashboard.charts.certificateTypes': 'Certificate Types',
    'dashboard.charts.agentPerformanceTrends': 'Customer Agent Performance Trends',
    'dashboard.charts.totalAgentPerformance': 'Total Agent Performance',
    'dashboard.charts.allAgents': 'All Agents',
    'dashboard.charts.agents': 'Agents',
    'dashboard.charts.top': 'Top',
    'dashboard.charts.newCustomers': 'New Customers',
    'dashboard.charts.conversions': 'Conversions',
    'dashboard.charts.count': 'Count',
    'dashboard.charts.lastDays': 'Last {days} days',
    'dashboard.charts.myPipeline': 'My Pipeline Status',
    'dashboard.charts.performanceSummary': 'Performance Summary',
    'dashboard.charts.all': 'All',
    'dashboard.charts.view': 'View:',
    'dashboard.charts.latestNew': 'Latest New',
    'dashboard.charts.totalNow': 'Total Now',
    'dashboard.charts.allMonths': 'All Months',
    'dashboard.charts.months.january': 'January',
    'dashboard.charts.months.february': 'February',
    'dashboard.charts.months.march': 'March',
    'dashboard.charts.months.april': 'April',
    'dashboard.charts.months.may': 'May',
    'dashboard.charts.months.june': 'June',
    'dashboard.charts.months.july': 'July',
    'dashboard.charts.months.august': 'August',
    'dashboard.charts.months.september': 'September',
    'dashboard.charts.months.october': 'October',
    'dashboard.charts.months.november': 'November',
    'dashboard.charts.months.december': 'December',
    'dashboard.charts.noLeaderboardData': 'No leaderboard data available',
    'dashboard.charts.dailyWorkProgress': 'Daily Work Progress',
    'dashboard.charts.statusChanges': 'Status Changes',
    'dashboard.charts.days': 'days',
    'dashboard.charts.last': 'Last',

    // Analytics Regenerate
    'dashboard.analytics.refresh': 'Regenerate Analytics Data',
    'dashboard.analytics.refreshButton': 'Regenerate Data',
    'dashboard.analytics.refreshSuccessTitle': 'Regeneration Complete',
    'dashboard.analytics.refreshSuccess': 'Analytics data regenerated successfully!\n\nScripts executed: {total}\nSuccessful: {successful}\nDuration: {duration}s',
    'dashboard.analytics.refreshFailedTitle': 'Regeneration Failed',
    'dashboard.analytics.refreshFailed': 'Failed to regenerate analytics data',
    'dashboard.analytics.refreshErrorTitle': 'Regeneration Error',
    'dashboard.analytics.refreshError': 'Error regenerating analytics data',

    // Analytics Update Recent
    'dashboard.analytics.updateRecent': 'Update Recent Analytics',
    'dashboard.analytics.updateRecentButton': 'Generate report data',
    'dashboard.analytics.updateRecentConfirmTitle': 'Confirm Update',
    'dashboard.analytics.updateRecentWarning': 'This will update analytics data for the last 12 months only.\n\nHistorical data older than 12 months will not be modified.\n\nContinue?',
    'dashboard.analytics.updateRecentSuccessTitle': 'Update Complete',
    'dashboard.analytics.updateRecentSuccess': 'Recent analytics updated successfully!\n\nScripts executed: {total}\nSuccessful: {successful}\nDuration: {duration}s',
    'dashboard.analytics.updateRecentFailedTitle': 'Update Failed',
    'dashboard.analytics.updateRecentFailed': 'Failed to update recent analytics',
    'dashboard.analytics.updateRecentErrorTitle': 'Update Error',
    'dashboard.analytics.updateRecentError': 'Error updating recent analytics',

    // User Approvals
    'approvals.pending': 'Pending Approvals',
    'approvals.approved': 'Approved Users',
    'approvals.rejected': 'Rejected Users',
    'approvals.phone': 'Phone Number',
    'approvals.status': 'Status',
    'approvals.requestDate': 'Request Date',
    'approvals.actions': 'Actions',
    'approvals.loadingRequests': 'Loading approval requests...',
    'approvals.approveFailed': 'Failed to approve user',
    'approvals.daysWaiting': 'Days Waiting',
    'approvals.days': 'days',
    'approvals.rejectionReason': 'Reason',
    'approvals.reasonRequired': '* Reason is required',
    'approvals.roleChangeHint': 'Optional: Change the user role if needed',
    'approvals.selectRole': 'Select role...',

    // User Management
    'userManagement.accountStatus': 'Account Status',
    'userManagement.enabled': 'Enabled',
    'userManagement.disabled': 'Disabled',
    'userManagement.enableUser': 'Enable User',
    'userManagement.disableUser': 'Disable User',
    'userManagement.enableTitle': 'Enable User Account',
    'userManagement.enableDescription': 'Enable account for',
    'userManagement.enableButton': 'Enable Account',
    'userManagement.enableReason': 'Enable reason (optional)',
    'userManagement.enablePlaceholder': 'e.g., Account reactivated after review...',
    'userManagement.disableTitle': 'Disable User Account',
    'userManagement.disableDescription': 'Disable account for',
    'userManagement.disableButton': 'Disable Account',
    'userManagement.disableReason': 'Disable reason *',
    'userManagement.disablePlaceholder': 'e.g., Temporary suspension, policy violation...',
    'userManagement.cannotDisableSelf': 'Cannot disable your own account',
    'userManagement.resetPassword': 'Reset Password',
    'userManagement.resetPasswordConfirm': 'Confirm Password Reset',
    'userManagement.resetPasswordConfirmMessage': 'Are you sure you want to reset the password for',
    'userManagement.resetPasswordConfirmButton': 'Reset Password',
    'userManagement.resetPasswordWarning': 'This action will reset the user\'s password and force them to change it on next login.',
    'userManagement.resetPasswordConsequences': 'The user will be logged out of all current sessions and will need to use the new temporary password to login.',
    'userManagement.passwordResetSuccess': 'Password Reset Successful',
    'userManagement.passwordResetSuccessMessage': 'Password has been reset for',
    'userManagement.temporaryPassword': 'Temporary Password',
    'userManagement.copyPassword': 'Copy Password',
    'userManagement.copy': 'Copy',
    'userManagement.copied': 'Copied!',
    'userManagement.important': 'Important',
    'userManagement.passwordResetWarning': 'This temporary password will only be shown once. Please save it securely and share it with the user.',
    'userManagement.allUsers': 'All Users',
    'userManagement.userApprovals': 'User Approvals',
    'userManagement.active': 'ACTIVE',
    'userManagement.activeUsers': 'Active Users',
    'userManagement.disabledUsers': 'Disabled Users',
    'userManagement.activeRate': 'Active Rate',

    // Customer Detail
    'detail.statusHistory': 'Status History',
    'detail.noHistory': 'No status history available',
    'detail.loadingHistory': 'Loading status history...',
    'detail.errorHistory': 'Error loading status history'
  },
  'zh-CN': {
    // Common
    'common.close': '关闭',


    // Settings
    'settings.title': '设置',
    'settings.language': '语言',
    'settings.language.en': 'English',
    'settings.language.zh-CN': '简体中文',

    // Customer Management
    'customer.name': '姓名',
    'customer.currentStatus': '当前状态',
    'customer.salesPerson': '业务经理',

    // Status
    'status.new': '新用户',
    'status.notified': '已提醒复审',
    'status.aborted': '客户放弃',
    'status.submitted': '已提交资料',
    'status.certified': '已发证',
    'status.certifiedElsewhere': '已在别处复审',

    // Approval Status
    'approvalStatus.pending': '待审批',
    'approvalStatus.approved': '已批准',
    'approvalStatus.rejected': '已拒绝',

    // Dashboard

    // Auth
    'auth.logout': '退出登录',
    'auth.phone': '电话',
    'auth.password': '密码',
    'auth.registerFailed': '注册失败',
    'auth.welcomeBack': '欢迎回来',
    'auth.signInToAccount': '登录到您的业务经理账户',
    'auth.phoneNumber': '手机号码',
    'auth.enterPhone': '请输入您的手机号码',
    'auth.enterPassword': '请输入您的密码',
    'auth.signingIn': '登录中...',
    'auth.signIn': '登录',
    'auth.dontHaveAccount': '还没有账户？',
    'auth.createAccount': '创建账户',
    'auth.registrationComplete': '注册完成！',
    'auth.customerTracker': '客户跟踪系统',

    // Change Password
    'password.title': '修改密码',
    'password.forcedTitle': '修改您的密码',
    'password.forcedChangeMessage': '出于安全原因，您必须修改密码后才能继续使用。',
    'password.label.currentPassword': '当前密码',
    'password.label.newPassword': '新密码',
    'password.label.confirmPassword': '确认新密码',
    'password.placeholder.currentPassword': '请输入当前密码',
    'password.placeholder.newPassword': '请输入新密码',
    'password.placeholder.confirmPassword': '请确认新密码',
    'password.button.change': '修改密码',
    'password.button.continue': '继续',
    'password.button.changing': '修改中...',
    'password.button.cancel': '取消',
    'password.requirements.title': '密码要求',
    'password.requirements.length': '至少6个字符',
    'password.requirements.different': '必须与当前密码不同',
    'password.requirements.met': '密码符合要求',
    'password.success.changed': '密码修改成功',
    'password.error.currentPasswordRequired': '请输入当前密码',
    'password.error.newPasswordRequired': '请输入新密码',
    'password.error.confirmPasswordRequired': '请确认新密码',
    'password.error.passwordTooShort': '密码至少需要6个字符',
    'password.error.passwordsDoNotMatch': '两次输入的密码不一致',
    'password.error.failed': '修改密码失败',

    // Error messages
    'error.phonePasswordRequired': '手机号码和密码为必填项',
    'error.incorrectCredentials': '手机号码或密码错误。请检查您的凭据并重试。',
    'error.networkError': '无法连接到服务器。请检查您的网络连接并重试。',
    'error.unexpectedError': '发生意外错误。请重试。',
    'error.loginFailed': '登录失败',
    'error.invalidCredentials': '凭据无效',
    'error.accountPending': '账户等待审批',
    'error.accountDenied': '账户访问被拒绝',
    'error.accountDisabled': '您的账户已被管理员禁用。请联系技术支持获取帮助。',
    'error.connectionError': '连接错误',
    'error.dismissMessage': '关闭错误消息',
    'error.phoneAlreadyExists': '手机号码已存在',
    'error.duplicateCustomerCertificate': '该手机号码已经有此类型的证件，请编辑现有客户资料或选择不同的证件类型。',
    'error.invalidToken': '无效或过期的令牌',
    'error.invalidResponse': '服务器响应无效',
    'error.updateFailed': '更新失败',
    'error.sessionConflict': '您已在其他设备登录，当前会话已失效。',
    'error.sessionConflictTitle': '由于新登录而退出',

    // Error help messages
    'error.tips': '提示：',
    'error.whatHappened': '发生了什么：',
    'error.sessionConflictExplanation': '您的账户在另一台设备上登录，导致您从当前会话中自动退出。',
    'error.sessionCanRelogin': '您可以重新登录以继续使用此设备。',
    'error.checkPhoneFormat': '请仔细检查您的手机号码格式',
    'error.ensurePassword': '确保您的密码正确',
    'error.capsLock': '确保未启用大写锁定',
    'error.whatToDo': '下一步操作：',
    'error.waitApproval': '请等待管理员审批',
    'error.contactAdmin': '如需立即访问请联系管理员',
    'error.tryAgainLater': '稍后再次尝试登录',
    'error.needHelp': '需要帮助？',
    'error.contactSystemAdmin': '联系系统管理员讨论您的账户状态并请求访问权限。',
    'error.trySteps': '尝试以下步骤：',
    'error.checkConnection': '检查您的网络连接',
    'error.refreshPage': '刷新页面并重试',
    'error.contactSupport': '如果问题持续存在，请联系技术支持',

    // Navigation
    'nav.adminDashboard': '统计报表',
    'nav.dashboard': '报表',
    'nav.customers': '客户',
    'nav.batchImport': '批量导入',
    'nav.settings': '设置',
    'nav.userManagement': '用户管理',
    'nav.refresh': '刷新',
    'nav.refreshing': '刷新中...',

    // Landing Page
    'landing.welcome': '欢迎',
    'landing.welcomeMessage': '欢迎使用客户管理系统，今天可以开始以下操作。',
    'landing.quickAccess': '快速访问',
    'landing.availableActions': '可用操作',
    'landing.yourRole': '您的角色',
    'landing.accountStatus': '账户活跃',
    'landing.systemStatus': '系统状态',
    'landing.online': '在线',
    'landing.ready': '就绪',
    'landing.quickActions': '快速操作',
    'landing.manageCustomers': '客户管理',
    'landing.manageCustomersDesc': '查看、添加、编辑和管理客户信息',
    'landing.viewDashboardDesc': '查看分析报告和绩效指标',
    'landing.batchImportDesc': '批量导入或导出客户数据',
    'landing.userManagementDesc': '管理用户审批和权限',
    'landing.gettingStarted': '快速入门',
    'landing.tip1': '点击"客户管理"查看和管理您的客户列表',
    'landing.tip2': '使用仪表板跟踪绩效和查看统计数据',
    'landing.tip3': '从侧边栏底部访问设置来管理您的账户',

    // General

    // App
    'app.customerTracker': '客户跟踪系统',
    'app.admin': '（管理员）',

    // Customer List
    'customers.addCustomer': '添加客户',
    'customers.searchPlaceholder': '按姓名或电话搜索...',
    'customers.search': '搜索',
    'customers.all': '全部',
    'customers.searchStatus': '状态',
    'customers.startDate': '开始日期',
    'customers.endDate': '结束日期',
    'customers.clear': '清除',
    'customers.errorLoading': '加载客户时出错',
    'customers.tryAgain': '重试',
    'customers.loadingCustomers': '正在加载客户...',
    'customers.noCustomersFound': '未找到客户',
    'customers.adjustSearch': '请调整搜索条件',
    'customers.getStartedFirst': '开始添加您的第一个客户',
    'customers.clearSearch': '清除搜索',
    'customers.of': '个，共',
    'customers.showing': '显示',
    'customers.to': '到',
    'customers.customers': '个客户',
    'customers.show': '显示：',
    'customers.perPage': '每页',
    'customers.name': '姓名',
    'customers.phone': '电话',
    'customers.cancel': '取消',
    'customers.confirm': '确认',
    'customers.close': '关闭',
    'customers.ok': '确定',
    'customers.detail.customer': '客户',

    // Customer Form
    'customers.form.createCustomer': '创建客户',
    'customers.form.name': '姓名',
    'customers.form.phone': '手机号码',
    'customers.form.certificateIssuer': '发证机关',
    'customers.form.businessReq': '备注',
    'customers.form.certificateType': '证件类型',
    'customers.form.age': '年龄',
    'customers.form.education': '教育程度',
    'customers.form.gender': '性别',
    'customers.form.gender.male': '男',
    'customers.form.gender.female': '女',
    'customers.form.gender.other': '其他',
    'customers.form.gender.select': '选择性别',
    'customers.form.address': '地址',
    'customers.form.salesPerson': '添加人',
    'customers.form.salesPerson.unknown': '未知',
    'customers.form.salesPerson.you': '您',
    'customers.form.customerAgent': '业务经理',
    'customers.form.customerAgent.placeholder': '输入经理名字',
    'customers.form.customerType': '客户类型',
    'customers.detail.statusManagement': '状态管理',
    'customers.detail.updateStatus': '更新状态',
    'customers.detail.updating': '更新中...',
    'detail.initialStatus': '初始状态：',
    'customers.detail.businessComplete': '业务流程已完成 - 不允许进一步转换',
    'customers.detail.loadingTransitions': '正在加载可用转换...',
    'customers.detail.initialCreation': '初始创建客户',
    'customers.detail.statusReason': '输入状态变更原因...',
    'customers.detail.reasonOptional': '原因（可选）',
    'customers.detail.newStatus': '新状态',
    'customers.detail.noTransitionsAvailable': '无可用状态转换',
    'customers.detail.selectEducationLevel': '选择教育水平',
    'customers.detail.notSpecified': '未指定',

    // Education Levels
    'education.elementary': '小学',
    'education.middleSchool': '初中',
    'education.highSchool': '高中',
    'education.secondaryVocational': '中专',
    'education.associate': '大专',
    'education.bachelor': '学士学位',
    'education.master': '硕士学位',
    'education.doctorate': '博士学位',
    'education.professional': '专业学位',
    'education.certificate': '证书/文凭',
    'education.other': '其他',
    // Customer Type
    'customerType.newCustomer': '新报名客户',
    'customerType.renewCustomer': '复审客户',
    // Crane & Machinery Types (起重机械)
    'certificateType.q1Command': 'Q1指挥',
    'certificateType.q2MobileCrane': 'Q2流动式',
    'certificateType.q2BridgeCrane': 'Q2桥式',
    'certificateType.q2GantryCrane': 'Q2门式',
    'certificateType.q2TowerCrane': 'Q2塔式',
    'certificateType.q2Hoist': 'Q2升降机',

    // Forklift & Industrial Vehicles
    'certificateType.n1Forklift': 'N1叉车',
    'certificateType.n2SightseeingCar': 'N2观光车',

    // Boiler & Pressure Vessels (锅炉压力容器)
    'certificateType.g1IndustrialBoiler': 'G1工业锅炉',
    'certificateType.g3BoilerWaterTreatment': 'G3锅炉水处理',
    'certificateType.r1QuickOpenPressureVessel': 'R1快开门式压力容器',
    'certificateType.r2MobilePressureVessel': 'R2移动式压力容器',
    'certificateType.pGasFilling': 'P气瓶充装',

    // Safety Management
    'certificateType.aSpecialEquipmentSafety': 'A特种设备安全管理',

    // Elevator Operations
    'certificateType.tElevatorOperation': 'T电梯作业',

    // Construction Trades (建筑施工)
    'certificateType.constructionElectrician': '建筑电工',
    'certificateType.constructionWelder': '建筑焊工',
    'certificateType.constructionScaffolder': '建筑架子工',
    'certificateType.constructionLiftingEquipment': '建筑起重机械操作类',
    'certificateType.constructionSignalman': '建筑起重信号司索工',
    'certificateType.constructionMaterialHoistDriver': '建筑物料提升机司机',
    'certificateType.constructionGondolaInstaller': '建筑吊篮安装拆卸工',

    // Electrical Operations (电工作业)
    'certificateType.lowVoltageElectrician': '低压电工作业',
    'certificateType.weldingThermalCutting': '焊接与热切割作业',
    'certificateType.highVoltageElectrician': '高压电工作业',

    // High-Altitude Work (高处作业)
    'certificateType.highAltitudeInstallation': '高处安装，维护，拆除作业',
    'certificateType.highAltitudeScaffolding': '登高架设作业',

    // Specialized Operations
    'certificateType.refrigerationAirConditioning': '制冷与空调作业',

    // Mining & Industry Safety (矿山安全作业)
    'certificateType.coalMineSafety': '煤矿安全作业',
    'certificateType.metalNonmetalMineSafety': '金属非金属矿山安全作业',

    // Petroleum & Chemical Safety (石油化工安全)
    'certificateType.oilGasSafety': '石油天然气安全作业',
    'certificateType.hazardousChemicalsSafety': '危险化学品安全作业',
    'certificateType.metallurgySafety': '冶金（有色）生产安全作业',
    'certificateType.fireworksSafety': '烟花爆竹安全作业',

    // Other types for backward compatibility
    'certificateType.others': '其它',
    'customers.form.selectCertificateType': '选择证件类型',
    'certificateIssuer.marketSupervisionAdministration': '市场监督管理局',
    'certificateIssuer.housingConstructionBureau': '住建局',
    'certificateIssuer.emergencyManagementDepartment': '应急管理厅',
    'certificateIssuer.other': '其它',
    'approvals.showing': '显示',
    'approvals.to': '到',
    'approvals.of': '共',
    'approvals.users': '个用户',
    'approvals.show': '显示：',
    'approvals.perPage': '每页',
    'approvals.noUsersFound': '未找到用户',
    'approvals.noUsersFoundMatching': '未找到匹配的用户',
    'approvals.noUsersWithStatus': '未找到状态为',
    'approvals.approveUser': '批准用户',
    'approvals.rejectUser': '拒绝用户',
    'approvals.resetToPending': '重置为待审批',
    'approvals.firstPage': '第一页',
    'approvals.previousPage': '上一页',
    'approvals.nextPage': '下一页',
    'approvals.lastPage': '最后一页',
    'approvals.approveTitle': '批准用户注册',
    'approvals.approveDescription': '批准注册',
    'approvals.approveButton': '批准用户',
    'approvals.approveReason': '批准原因（可选）',
    'approvals.approvePlaceholder': '例如：申请看起来不错，已验证身份...',
    'approvals.rejectTitle': '拒绝用户注册',
    'approvals.rejectDescription': '拒绝注册',
    'approvals.rejectButton': '拒绝用户',
    'approvals.rejectReason': '拒绝原因 *',
    'approvals.rejectPlaceholder': '例如：申请不完整，验证失败...',
    'approvals.resetTitle': '重置用户状态',
    'approvals.resetDescription': '重置',
    'approvals.resetDescription2': '状态为待审批？',
    'approvals.resetButton': '重置状态',
    'approvals.resetReason': '重置原因（可选）',
    'approvals.resetPlaceholder': '例如：需要重新审核申请...',
    'approvals.processing': '处理中...',
    'dashboard.sales.myConversionRate': '我的转化率',
    'dashboard.sales.conversionProgress': '转化进度',
    'dashboard.sales.conversionRate': '转化率',
    'dashboard.sales.keyMetrics': '关键指标',
    'dashboard.sales.newCustomers': '每月业务量',
    'dashboard.sales.conversions': '成交',
    'dashboard.sales.rate': '率',
    'dashboard.sales.quickActions': '快速操作',
    'dashboard.sales.viewAllCustomers': '查看所有客户',
    'dashboard.sales.followUpCalls': '跟进电话',
    'dashboard.sales.pendingOrders': '待处理订单',
    'customers.form.idCard': '身份证',
    'customers.form.idCardPlaceholder': '请输入身份证号',
    'customers.form.idCardHelp': '仅允许输入数字和英文字母',
    'customers.form.noIdCard': '未填写身份证',
    'customers.form.certifiedAt': '取证日期',
    'customers.form.certifiedAt.placeholder': '选择取证日期',
    'customers.form.creating': '创建中...',
    'customers.form.create': '创建客户',
    'customers.form.updating': '更新中...',
    'customers.form.update': '更新客户',
    'customers.form.cancel': '取消',

    // Batch Import
    'batchImport.uploadExcel': '上传Excel文件',
    'batchImport.selectFile': '选择Excel文件',
    'batchImport.remove': '移除',
    'batchImport.uploading': '上传中...',
    'batchImport.uploadFailed': '上传文件失败，请重试。',
    'batchImport.status': '状态',
    'batchImport.cancelClear': '取消并清除',
    'batchImport.confirmImport': '确认导入',
    'batchImport.importing': '导入中...',
    'batchImport.cancelling': '取消中...',
    'batchImport.pleaseWait': '请稍候...',
    'batchImport.newCustomersImported': '新导入客户',
    'batchImport.customersUpdated': '更新客户',
    'batchImport.skipped': '跳过（重复/无效）',
    'batchImport.newToImport': '新增导入',
    'batchImport.toUpdate': '待更新',
    'batchImport.duplicates': '重复',
    'batchImport.invalid': '无效',
    'batchImport.uploadNow': '立即上传',
    'batchImport.permissionDenied': '权限被拒绝',
    'batchImport.noPermissionMessage': '您没有权限访问批量导入功能。',
    'batchImport.status.valid': '有效',
    'batchImport.status.update': '更新',
    'batchImport.status.duplicate': '重复',
    'batchImport.status.invalid': '无效',
    'batchImport.validationMessage': '验证信息',
    'batchImport.confirmNewFileTitle': '未确认的数据',
    'batchImport.confirmNewFileMessage': '仍有未确认导入的数据，您确定要选择新文件吗？',
    'batchImport.confirmNewFileYes': '是的，清除并选择新文件',
    'batchImport.confirmNewFileNo': '不，保留当前数据',
    'batchImport.updateFilterInfo': '红色文字显示的内容将更新到现有客户记录。',

    // Customer Detail
    'customers.detail.customerDetails': '客户详情',
    'customers.detail.edit': '编辑',
    'customers.detail.back': '返回列表',
    'customers.detail.loading': '正在加载客户详情...',
    'customers.detail.notFound': '客户未找到',
    'customers.detail.failedLoad': '加载客户详情失败',
    'customers.detail.statusTransitionFailed': '状态更改失败',
    'customers.updateSuccess': '客户更新成功',

    // Registration
    'register.createAccount': '创建账户',
    'register.joinPlatform': '加入我们的客户管理平台',
    'register.allFieldsRequired': '所有字段都是必填的',
    'register.passwordsDontMatch': '密码不匹配',
    'register.passwordTooShort': '密码至少需要6个字符',
    'register.confirmPassword': '确认密码',
    'register.enterConfirmPassword': '确认您的密码',
    'register.creating': '创建账户中...',
    'register.alreadyHaveAccount': '已有账户？',
    'register.signIn': '登录',
    'register.createPassword': '创建密码',
    'register.minimumChars': '至少6个字符',
    'register.selectRole': '选择角色',
    'register.role': '角色',

    // Roles
    'role.admin': '管理员',
    'role.officer': '文员',
    'role.customerAgent': '业务经理',

    // Delete Requests
    'deleteRequests.title': '客户删除请求',
    'deleteRequests.loadingRequests': '加载删除请求中...',
    'deleteRequests.requestedBy': '请求人',
    'deleteRequests.reason': '原因',
    'deleteRequests.requestedAt': '请求时间',
    'deleteRequests.approve': '批准',
    'deleteRequests.reject': '拒绝',
    'deleteRequests.requestDeletion': '请求删除',
    'deleteRequests.requestDeleteSuccess': '删除请求提交成功',
    'deleteRequests.requestDeleteError': '提交删除请求失败',
    'deleteRequests.pendingRequestExists': '该客户已有一个待处理的删除请求',
    'deleteRequests.requestSubmitted': '请求已提交',
    'deleteRequests.reasonRequired': '原因为必填项',
    'deleteRequests.reasonPlaceholder': '请提供删除请求的原因...',
    'deleteRequests.submitting': '提交中...',
    'deleteRequests.pending': '待处理',
    'deleteRequests.approved': '已批准',
    'deleteRequests.rejected': '已拒绝',
    'deleteRequests.rejectionReason': '拒绝原因',
    'deleteRequests.searchPlaceholder': '按姓名、电话或请求人搜索',
    'deleteRequests.noRequestsFound': '未找到删除请求',
    'deleteRequests.noRequestsMatching': '未找到匹配的删除请求',
    'deleteRequests.noPendingRequests': '没有待处理的删除请求',
    'deleteRequests.noApprovedRequests': '没有已批准的删除请求',
    'deleteRequests.noRejectedRequests': '没有已拒绝的删除请求',
    'deleteRequests.approveFailed': '批准请求失败',
    'deleteRequests.rejectFailed': '拒绝请求失败',
    'deleteRequests.rejectRequest': '拒绝删除请求',
    'deleteRequests.rejectionReasonRequired': '拒绝原因为必填项',
    'deleteRequests.rejectionReasonPlaceholder': '请提供拒绝原因...',
    'deleteRequests.rejectionReasonHelp': '该原因将对请求人可见',
    'deleteRequests.rejecting': '拒绝中...',
    'deleteRequests.approveRequest': '批准删除请求',
    'deleteRequests.approvalReason': '批准原因',
    'deleteRequests.approvalReasonPlaceholder': '可选：添加批准意见或原因...',
    'deleteRequests.approvalReasonHelp': '该意见将对请求人可见',
    'deleteRequests.approving': '批准中...',
    'deleteRequests.optional': '可选',
    'deleteRequests.requests': '个请求',

    // Permission Errors
    'error.permissionDenied': '权限不足',
    'error.onlyAdminAndAgentCanAdd': '只有管理员和业务经理可以添加客户',

    // Registration Success
    'register.success.title': '注册成功！',
    'register.success.message': '您的账户已创建，正在等待审批。',
    'register.success.adminReview': '管理员将很快审核您的请求。',
    'register.success.notification': '账户获得批准后将通知您。',
    'register.success.backToLogin': '返回登录',

    // Validation messages
    'validation.certificateTypeRequired': '证件类型为必填项',
    'validation.idCardRequired': '身份证为必填项',

    // Common actions

    // Dashboard - Admin
    'dashboard.admin.backToCustomers': '返回客户',

    // Dashboard - Sales

    // Dashboard - Metrics
    'dashboard.metrics.totalCustomers': '成交总量',
    'dashboard.metrics.newCustomers': '每月业务量',
    'dashboard.metrics.unsettled': '未成交量',
    'dashboard.metrics.conversionRate': '转化率',
    'dashboard.metrics.newCustomers30d': '当月成交总量',
    'dashboard.metrics.fromLastPeriod': '对比上期',
    'dashboard.metrics.recentActivity': '尚未发证或已在别处办理',
    'dashboard.metrics.loadingDashboard': '正在加载报表...',
    'dashboard.metrics.errorLoadingDashboard': '加载报表时出错',
    'dashboard.metrics.viewCustomers': '查看客户',
    'dashboard.metrics.myCustomers': '我的客户',

    // Dashboard - Charts
    'dashboard.charts.statusDistribution': '未复审客户状态分布',
    'dashboard.charts.trends': '成交量趋势',
    'dashboard.charts.noData': '暂无数据',
    'dashboard.charts.error': '错误',
    'dashboard.charts.errorLoading': '图表加载出错',
    'dashboard.charts.refresh': '刷新报表',
    'dashboard.charts.total': '总计',
    'dashboard.charts.totalLabel': '总计',
    'dashboard.charts.totalCustomers': '总计',
    'dashboard.charts.customers': '客户',
    'dashboard.charts.ofTotal': '占总数',
    'dashboard.charts.quickStats': '快速统计',
    'dashboard.charts.highestCount': '最高数量',
    'dashboard.charts.statusTypes': '状态类型',
    'dashboard.charts.dataWillAppear': '客户状态数据可用时将显示在此处',
    'dashboard.charts.newCertifications': '月成交量',
    'dashboard.charts.conversionRate': '转化率 (%)',
    'dashboard.charts.leaderboard': '业务经理业绩榜单',
    'dashboard.charts.certificateTypeTrends': '证件类型趋势',
    'dashboard.charts.selectCertificateTypes': '选择证件类型',
    'dashboard.charts.allCertificateTypes': '所有证件类型',
    'dashboard.charts.certificateTypes': '证件类型',
    'dashboard.charts.agentPerformanceTrends': '业务经理月业绩趋势',
    'dashboard.charts.totalAgentPerformance': '业务经理总业绩趋势',
    'dashboard.charts.allAgents': '所有业务经理',
    'dashboard.charts.agents': '业务经理',
    'dashboard.charts.top': '前',
    'dashboard.charts.newCustomers': '新增客户',
    'dashboard.charts.conversions': '成交',
    'dashboard.charts.count': '数量',
    'dashboard.charts.lastDays': '最近 {days} 天',
    'dashboard.charts.myPipeline': '我的管道状态',
    'dashboard.charts.performanceSummary': '绩效摘要',
    'dashboard.charts.all': '全部',
    'dashboard.charts.view': '查看：',
    'dashboard.charts.latestNew': '最新新增',
    'dashboard.charts.totalNow': '当前总数',
    'dashboard.charts.allMonths': '全年',
    'dashboard.charts.months.january': '一月',
    'dashboard.charts.months.february': '二月',
    'dashboard.charts.months.march': '三月',
    'dashboard.charts.months.april': '四月',
    'dashboard.charts.months.may': '五月',
    'dashboard.charts.months.june': '六月',
    'dashboard.charts.months.july': '七月',
    'dashboard.charts.months.august': '八月',
    'dashboard.charts.months.september': '九月',
    'dashboard.charts.months.october': '十月',
    'dashboard.charts.months.november': '十一月',
    'dashboard.charts.months.december': '十二月',
    'dashboard.charts.noLeaderboardData': '暂无业绩榜单数据',
    'dashboard.charts.dailyWorkProgress': '每日工作进展',
    'dashboard.charts.statusChanges': '状态变更',
    'dashboard.charts.days': '天',
    'dashboard.charts.last': '最近',

    // Analytics Regenerate
    'dashboard.analytics.refresh': '重新生成报表数据',
    'dashboard.analytics.refreshButton': '重新生成',
    'dashboard.analytics.refreshSuccessTitle': '重新生成完成',
    'dashboard.analytics.refreshSuccess': '报表数据重新生成成功！\n\n执行脚本数: {total}\n成功: {successful}\n耗时: {duration}秒',
    'dashboard.analytics.refreshFailedTitle': '重新生成失败',
    'dashboard.analytics.refreshFailed': '重新生成报表数据失败',
    'dashboard.analytics.refreshErrorTitle': '重新生成错误',
    'dashboard.analytics.refreshError': '重新生成报表数据时出错',

    // Analytics Update Recent
    'dashboard.analytics.updateRecent': '更新近期分析数据',
    'dashboard.analytics.updateRecentButton': '重新生成报表数据',
    'dashboard.analytics.updateRecentConfirmTitle': '确认更新',
    'dashboard.analytics.updateRecentWarning': '请注意，该操作只能在上传新文件以后方可操作！\n\n这将仅更新最近12个月的分析数据，\n\n超过12个月的历史数据不会被修改。\n\n是否继续？',
    'dashboard.analytics.updateRecentSuccessTitle': '更新完成',
    'dashboard.analytics.updateRecentSuccess': '近期分析数据更新成功！\n\n执行脚本数: {total}\n成功: {successful}\n耗时: {duration}秒',
    'dashboard.analytics.updateRecentFailedTitle': '更新失败',
    'dashboard.analytics.updateRecentFailed': '更新近期分析数据失败',
    'dashboard.analytics.updateRecentErrorTitle': '更新错误',
    'dashboard.analytics.updateRecentError': '更新近期分析数据时出错',

    // User Approvals
    'approvals.pending': '待审批',
    'approvals.approved': '已批准用户',
    'approvals.rejected': '已拒绝用户',
    'approvals.phone': '手机号码',
    'approvals.status': '状态',
    'approvals.requestDate': '请求日期',
    'approvals.actions': '操作',
    'approvals.loadingRequests': '正在加载审批请求...',
    'approvals.approveFailed': '批准用户失败',
    'approvals.daysWaiting': '等待天数',
    'approvals.days': '天',
    'approvals.rejectionReason': '原因',
    'approvals.reasonRequired': '* 原因是必填的',
    'approvals.roleChangeHint': '可选：如需要可修改用户角色',
    'approvals.selectRole': '选择角色...',

    // User Management
    'userManagement.accountStatus': '账户状态',
    'userManagement.enabled': '已启用',
    'userManagement.disabled': '已禁用',
    'userManagement.enableUser': '启用用户',
    'userManagement.disableUser': '禁用用户',
    'userManagement.enableTitle': '启用用户账户',
    'userManagement.enableDescription': '启用账户',
    'userManagement.enableButton': '启用账户',
    'userManagement.enableReason': '启用原因（可选）',
    'userManagement.enablePlaceholder': '例如：审核后重新激活账户...',
    'userManagement.disableTitle': '禁用用户账户',
    'userManagement.disableDescription': '禁用账户',
    'userManagement.disableButton': '禁用账户',
    'userManagement.disableReason': '禁用原因 *',
    'userManagement.disablePlaceholder': '例如：临时暂停，违反政策...',
    'userManagement.cannotDisableSelf': '不能禁用自己的账户',
    'userManagement.resetPassword': '重置密码',
    'userManagement.resetPasswordConfirm': '确认密码重置',
    'userManagement.resetPasswordConfirmMessage': '确定要重置以下用户的密码吗',
    'userManagement.resetPasswordConfirmButton': '重置密码',
    'userManagement.resetPasswordWarning': '此操作将重置用户密码并强制他们在下次登录时修改密码。',
    'userManagement.resetPasswordConsequences': '用户将被登出所有当前会话，需要使用新的临时密码登录。',
    'userManagement.passwordResetSuccess': '密码重置成功',
    'userManagement.passwordResetSuccessMessage': '密码已重置',
    'userManagement.temporaryPassword': '临时密码',
    'userManagement.copyPassword': '复制密码',
    'userManagement.copy': '复制',
    'userManagement.copied': '已复制！',
    'userManagement.important': '重要提示',
    'userManagement.passwordResetWarning': '此临时密码仅显示一次。请妥善保存并与用户分享。',
    'userManagement.allUsers': '所有用户',
    'userManagement.userApprovals': '用户审批',
    'userManagement.active': '活跃',
    'userManagement.activeUsers': '活跃用户',
    'userManagement.disabledUsers': '已禁用用户',
    'userManagement.activeRate': '活跃率',

    // Customer Detail
    'detail.statusHistory': '状态历史',
    'detail.noHistory': '暂无状态历史',
    'detail.loadingHistory': '正在加载状态历史...',
    'detail.errorHistory': '加载状态历史时出错'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>('zh-CN');

  // Load language from sessionStorage on mount
  useEffect(() => {
    const savedLanguage = sessionStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh-CN')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Save language to sessionStorage when it changes
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    sessionStorage.setItem('language', newLanguage);
  };

  // Translation function with parameter support
  const t = (key: string, params?: Record<string, string | number>): string => {
    const languageTranslations = translations[language];
    let translation = languageTranslations[key as keyof typeof languageTranslations] || key;

    // Replace parameters in the translation string
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, String(params[param]));
      });
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
