'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh-CN';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  'en': {
    // Common
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.searching': 'Searching...',


    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.language.en': 'English',
    'settings.language.zh-CN': '简体中文',

    // Map Picker
    'map.selectLocation': 'Select Location',
    'map.searchPlaceholder': 'Search for a location...',
    'map.myLocation': 'My Location',
    'map.locating': 'Locating...',
    'map.selectedLocation': 'Selected Location',
    'map.noLocationSelected': 'No location selected',
    'map.clickToSelect': 'Click on the map or search for a location',
    'map.confirmSelection': 'Confirm Selection',
    'map.gettingAddress': 'Getting address...',
    'map.currentLocation': 'Current location',
    'map.location': 'Location',
    'map.unknown': 'Unknown',
    'map.china': 'China',
    'map.howToUse': 'How to use:',
    'map.howToUse1': 'My Location - Automatically center on your current position',
    'map.howToUse2': 'Search for a location',
    'map.howToUse3': 'Click on map to select location',
    'map.howToUse4': 'Review details and confirm',
    'map.loadingMap': 'Loading map...',
    'map.locationAccessDenied': 'Location access denied by user. Please allow location access in browser settings.',
    'map.locationUnavailable': 'Location information unavailable. Please check GPS or network connection.',
    'map.locationTimeout': 'Location request timed out. Please try again.',
    'map.locationError': 'Error getting location',
    'map.yourLocation': 'Your location:',

    // Customer Management
    'customer.addCustomer': 'Add Customer',
    'customer.editCustomer': 'Edit Customer',
    'customer.deleteCustomer': 'Delete Customer',
    'customer.restoreCustomer': 'Restore Customer',
    'customer.customerDetails': 'Customer Details',
    'customer.statusHistory': 'Status History',
    'customer.name': 'Name',
    'customer.phone': 'Phone',
    'customer.certificateIssuer': 'Certificate Issuer',
    'customer.businessRequirements': 'Comments',
    'customer.certificateType': 'Certificate Type',
    'customer.age': 'Age',
    'customer.education': 'Education',
    'customer.gender': 'Gender',
    'customer.location': 'Location',
    'customer.price': 'Price',
    'customer.currentStatus': 'Current Status',
    'customer.salesPerson': 'Business Manager',
    'customer.customerAgent': 'Business Manager',
    'customer.createdAt': 'Created At',
    'customer.updatedAt': 'Updated At',

    // Status
    'status.new': 'New',
    'status.notified': 'Notified',
    'status.aborted': 'Aborted',
    'status.submitted': 'Submitted',
    'status.certified': 'Certified',

    // Approval Status
    'approvalStatus.pending': 'Pending',
    'approvalStatus.approved': 'Approved',
    'approvalStatus.rejected': 'Rejected',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.totalCustomers': 'Total Customers',
    'dashboard.newCustomers': 'New Customers',
    'dashboard.activeCustomers': 'Active Customers',
    'dashboard.conversionRate': 'Conversion Rate',
    'dashboard.salesLeaderboard': 'Business Manager Leaderboard',
    'dashboard.performance': 'Performance',
    'dashboard.metrics': 'Metrics',

    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.phone': 'Phone',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginSuccess': 'Login successful',
    'auth.registerSuccess': 'Registration successful',
    'auth.loginFailed': 'Login failed',
    'auth.registerFailed': 'Registration failed',
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInToAccount': 'Sign in to your sales account',
    'auth.phoneNumber': 'Phone Number',
    'auth.enterPhone': 'Enter your phone number',
    'auth.enterPassword': 'Enter your password',
    'auth.signingIn': 'Signing In...',
    'auth.signIn': 'Sign In',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.createAccount': 'Create Account',
    'auth.registrationComplete': 'Registration Complete!',
    'auth.customerTracker': 'Customer Tracker',

    // Error messages
    'error.phonePasswordRequired': 'Phone and password are required',
    'error.incorrectCredentials': 'Incorrect phone number or password. Please check your credentials and try again.',
    'error.networkError': 'Unable to connect to the server. Please check your internet connection and try again.',
    'error.unexpectedError': 'An unexpected error occurred. Please try again.',
    'error.loginFailed': 'Login Failed',
    'error.invalidCredentials': 'Invalid Credentials',
    'error.accountPending': 'Account Pending Approval',
    'error.accountDenied': 'Account Access Denied',
    'error.accountDisabled': 'Your account has been disabled by an administrator. Please contact support for assistance.',
    'error.connectionError': 'Connection Error',
    'error.dismissMessage': 'Dismiss error message',
    'error.phoneAlreadyExists': 'Phone number already exists',
    'error.invalidToken': 'Invalid or expired token',
    'error.invalidResponse': 'Invalid response from server',

    // Error help messages
    'error.tips': 'Tips:',
    'error.checkPhoneFormat': 'Double-check your phone number format',
    'error.ensurePassword': 'Ensure your password is correct',
    'error.capsLock': 'Make sure Caps Lock is not enabled',
    'error.whatToDo': 'What to do next:',
    'error.waitApproval': 'Please wait for admin approval',
    'error.contactAdmin': 'Contact admin if you need immediate access',
    'error.tryAgainLater': 'Try logging in again later',
    'error.needHelp': 'Need help?',
    'error.contactSystemAdmin': 'Contact your system administrator to discuss your account status and request access.',
    'error.trySteps': 'Try these steps:',
    'error.checkConnection': 'Check your internet connection',
    'error.refreshPage': 'Refresh the page and try again',
    'error.contactSupport': 'Contact support if the problem persists',

    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.customers': 'Customers',
    'nav.settings': 'Settings',
    'nav.userApprovals': 'User Approvals',
    'nav.userManagement': 'User Management',
    'nav.refresh': 'Refresh',
    'nav.refreshing': 'Refreshing...',

    // General
    'general.admin': 'Admin',

    // App
    'app.customerTracker': 'Customer Tracker',
    'app.professionalCRM': 'Professional CRM Solution',
    'app.admin': '(Admin)',

    // Customer List
    'customers.management': 'Customer Management',
    'customers.manageTrack': 'Manage and track your customer relationships',
    'customers.addCustomer': 'Add Customer',
    'customers.searchFilter': 'Search & Filter',
    'customers.searchPlaceholder': 'Search by name or phone...',
    'customers.search': 'Search',
    'customers.searchStatus': 'Status',
    'customers.allStatuses': 'All Statuses',
    'customers.clearFilters': 'Clear',
    'customers.certifiedTimeRange': 'Certified Time Range',
    'customers.startDate': 'Start Date',
    'customers.endDate': 'End Date',
    'customers.clear': 'Clear',
    'customers.errorLoading': 'Error loading customers',
    'customers.tryAgain': 'Try Again',
    'customers.loadingCustomers': 'Loading customers...',
    'customers.noCustomersFound': 'No customers found',
    'customers.adjustSearch': 'Try adjusting your search terms',
    'customers.getStartedFirst': 'Get started by adding your first customer',
    'customers.clearSearch': 'Clear Search',
    'customers.customersFound': 'Customer',
    'customers.customersFoundPlural': 'Customers',
    'customers.found': 'Found',
    'customers.page': 'Page',
    'customers.of': 'of',
    'customers.pageInfo': 'Page {page} of {total}',
    'customers.showing': 'Showing',
    'customers.to': 'to',
    'customers.customers': 'customers',
    'customers.show': 'Show:',
    'customers.perPage': 'per page',
    'customers.previous': 'Previous',
    'customers.next': 'Next',
    'customers.name': 'Name',
    'customers.phone': 'Phone',
    'customers.cancel': 'Cancel',
    'customers.ok': 'OK',
    'customers.detail.customer': 'Customer',

    // Customer Form
    'customers.form.createCustomer': 'Create Customer',
    'customers.form.editCustomer': 'Edit Customer',
    'customers.form.customerInfo': 'Customer Information',
    'customers.form.name': 'Full Name',
    'customers.form.phone': 'Phone Number',
    'customers.form.certificateIssuer': 'Certificate Issuer',
    'customers.form.certificateIssuer.placeholder': 'Enter certificate issuer',
    'customers.form.businessReq': 'Comments',
    'customers.form.certificateType': 'Certificate Type',
    'customers.form.age': 'Age',
    'customers.form.education': 'Education Level',
    'customers.form.gender': 'Gender',
    'customers.form.gender.male': 'Male',
    'customers.form.gender.female': 'Female',
    'customers.form.gender.other': 'Other',
    'customers.form.gender.select': 'Select gender',
    'customers.form.location': 'Location',
    'customers.form.salesPerson': 'Added By',
    'customers.form.salesPerson.unknown': 'Unknown',
    'customers.form.salesPerson.you': 'You',
    'customers.form.salesPerson.admin': 'Admin',
    'customers.form.salesPerson.officer': 'Officer',
    'customers.form.salesPerson.customerAgent': 'Business Manager',
    'customers.form.customerAgent': 'Business Manager',
    'customers.form.customerAgent.placeholder': 'Enter agent name',
    'customers.detail.statusManagement': 'Status Management',
    'customers.detail.updateStatus': 'Update Status',
    'customers.detail.updating': 'Updating...',
    'detail.initialStatus': 'Initial status:',
    'customers.detail.businessComplete': 'Business process is complete - no further transitions allowed',
    'customers.detail.loadingTransitions': 'Loading available transitions...',
    'customers.detail.initialCreation': 'Initial customer creation',
    'customers.detail.statusReason': 'Enter reason for status change...',
    'customers.detail.reasonOptional': 'Reason (Optional)',
    'customers.detail.newStatus': 'New Status',
    'customers.detail.noTransitionsAvailable': 'No status transitions available',
    'customers.detail.selectEducationLevel': 'Select education level',
    'customers.detail.notSpecified': 'Not specified',

    // Education Levels
    'education.elementary': 'Elementary School',
    'education.middleSchool': 'Middle School',
    'education.highSchool': 'High School',
    'education.associate': 'Associate Degree',
    'education.bachelor': 'Bachelor\'s Degree',
    'education.master': 'Master\'s Degree',
    'education.doctorate': 'Doctorate/PhD',
    'education.professional': 'Professional Degree',
    'education.certificate': 'Certificate/Diploma',
    'education.other': 'Other',
    'certificateType.electrician': 'Electrician',
    'certificateType.welder': 'Welder',
    'certificateType.excavator': 'Excavator Operator',
    'customers.form.selectCertificateType': 'Select certificate type',
    'approvals.showing': 'Showing',
    'approvals.to': 'to',
    'approvals.of': 'of',
    'approvals.users': 'users',
    'approvals.show': 'Show:',
    'approvals.perPage': 'per page',
    'approvals.noUsersFound': 'No users found',
    'approvals.noUsersFoundMatching': 'No users found matching',
    'approvals.noUsersWithStatus': 'No users with status',
    'approvals.approveUser': 'Approve User',
    'approvals.rejectUser': 'Reject User',
    'approvals.resetToPending': 'Reset to Pending',
    'approvals.firstPage': 'First page',
    'approvals.previousPage': 'Previous page',
    'approvals.nextPage': 'Next page',
    'approvals.lastPage': 'Last page',
    'approvals.approveTitle': 'Approve User Registration',
    'approvals.approveDescription': 'Approve registration for',
    'approvals.approveButton': 'Approve User',
    'approvals.approveReason': 'Approval reason (optional)',
    'approvals.approvePlaceholder': 'e.g., Application looks good, verified identity...',
    'approvals.rejectTitle': 'Reject User Registration',
    'approvals.rejectDescription': 'Reject registration for',
    'approvals.rejectButton': 'Reject User',
    'approvals.rejectReason': 'Rejection reason *',
    'approvals.rejectPlaceholder': 'e.g., Incomplete application, verification failed...',
    'approvals.rejectRequired': '* Rejection reason is required',
    'approvals.resetTitle': 'Reset User Status',
    'approvals.resetDescription': 'Reset',
    'approvals.resetDescription2': 'status back to pending?',
    'approvals.resetButton': 'Reset Status',
    'approvals.resetReason': 'Reset reason (optional)',
    'approvals.resetPlaceholder': 'e.g., Need to review application again...',
    'approvals.processing': 'Processing...',
    'dashboard.sales.myConversionRate': 'My Conversion Rate',
    'dashboard.sales.conversionProgress': 'Conversion Progress',
    'dashboard.sales.conversionRate': 'conversion rate',
    'dashboard.sales.keyMetrics': 'Key Metrics',
    'dashboard.sales.newCustomers': 'New Customers',
    'dashboard.sales.conversions': 'Conversions',
    'dashboard.sales.rate': 'rate',
    'dashboard.sales.quickActions': 'Quick Actions',
    'dashboard.sales.viewAllCustomers': 'View All Customers',
    'dashboard.sales.followUpCalls': 'Follow Up Calls',
    'dashboard.sales.pendingOrders': 'Pending Orders',
    'customers.form.price': 'Price',
    'customers.form.certifiedAt': 'Certified Date',
    'customers.form.certifiedAt.placeholder': 'Select certification date',
    'customers.form.status': 'Initial Status',
    'customers.form.selectLocation': 'Select Location',
    'customers.form.creating': 'Creating...',
    'customers.form.create': 'Create Customer',
    'customers.form.updating': 'Updating...',
    'customers.form.update': 'Update Customer',
    'customers.form.cancel': 'Cancel',
    'customers.form.customerCreated': 'Customer created successfully!',
    'customers.form.customerUpdated': 'Customer updated successfully!',
    'customers.form.failedCreate': 'Failed to create customer',
    'customers.form.failedUpdate': 'Failed to update customer',
    'customers.form.requiredFields': 'Please fill in all required fields',

    // Customer Detail
    'customers.detail.customerDetails': 'Customer Details',
    'customers.detail.statusHistory': 'Status History',
    'customers.detail.personalInfo': 'Personal Information',
    'customers.detail.businessInfo': 'Business Information',
    'customers.detail.contactInfo': 'Contact Information',
    'customers.detail.edit': 'Edit',
    'customers.detail.delete': 'Delete',
    'customers.detail.restore': 'Restore',
    'customers.detail.back': 'Back to List',
    'customers.detail.loading': 'Loading customer details...',
    'customers.detail.notFound': 'Customer not found',
    'customers.detail.failedLoad': 'Failed to load customer details',
    'customers.detail.confirmDelete': 'Are you sure you want to delete this customer?',
    'customers.detail.confirmRestore': 'Are you sure you want to restore this customer?',
    'customers.detail.deleteSuccess': 'Customer deleted successfully',
    'customers.detail.restoreSuccess': 'Customer restored successfully',

    // Registration
    'register.createAccount': 'Create Account',
    'register.joinPlatform': 'Join our customer management platform',
    'register.allFieldsRequired': 'All fields are required',
    'register.passwordsDontMatch': 'Passwords do not match',
    'register.passwordTooShort': 'Password must be at least 6 characters long',
    'register.confirmPassword': 'Confirm Password',
    'register.enterConfirmPassword': 'Confirm your password',
    'register.creating': 'Creating Account...',
    'register.alreadyHaveAccount': 'Already have an account?',
    'register.signIn': 'Sign In',
    'register.createPassword': 'Create a password',
    'register.minimumChars': 'Minimum 6 characters',
    'register.selectRole': 'Select Role',
    'register.role': 'Role',

    // Roles
    'role.admin': 'Admin',
    'role.officer': 'Officer',
    'role.customerAgent': 'Business Manager',

    // Delete Requests
    'deleteRequests.title': 'Customer Delete Requests',
    'deleteRequests.subtitle': 'Review and manage customer deletion requests',
    'deleteRequests.noRequests': 'No pending delete requests',
    'deleteRequests.loadingRequests': 'Loading delete requests...',
    'deleteRequests.requestedBy': 'Requested by',
    'deleteRequests.customer': 'Customer',
    'deleteRequests.reason': 'Reason',
    'deleteRequests.requestedAt': 'Requested',
    'deleteRequests.status': 'Status',
    'deleteRequests.actions': 'Actions',
    'deleteRequests.approve': 'Approve',
    'deleteRequests.reject': 'Reject',
    'deleteRequests.approveSuccess': 'Delete request approved',
    'deleteRequests.rejectSuccess': 'Delete request rejected',
    'deleteRequests.confirmApprove': 'Are you sure you want to approve this request? This will delete the customer.',
    'deleteRequests.confirmReject': 'Are you sure you want to reject this request?',
    'deleteRequests.requestDeletion': 'Request Deletion',
    'deleteRequests.requestDeleteSuccess': 'Delete request submitted successfully',
    'deleteRequests.requestDeleteError': 'Failed to submit delete request',
    'deleteRequests.pendingRequestExists': 'A pending delete request already exists for this customer',
    'deleteRequests.requestSubmitted': 'Request Submitted',
    'deleteRequests.reasonRequired': 'Reason is required',
    'deleteRequests.reasonPlaceholder': 'Please provide a reason for the deletion request...',
    'deleteRequests.submitting': 'Submitting...',
    'deleteRequests.pending': 'Pending',
    'deleteRequests.approved': 'Approved',
    'deleteRequests.rejected': 'Rejected',
    'deleteRequests.rejectionReason': 'Rejection Reason',
    'deleteRequests.all': 'All',
    'deleteRequests.pendingRequests': 'Pending Delete Requests',
    'deleteRequests.pendingRequestsDescription': 'Review and approve or reject customer deletion requests',
    'deleteRequests.searchPlaceholder': 'Search by name, phone, or requester',
    'deleteRequests.noRequestsFound': 'No delete requests found',
    'deleteRequests.noRequestsMatching': 'No delete requests matching',
    'deleteRequests.noPendingRequests': 'No pending delete requests',
    'deleteRequests.noApprovedRequests': 'No approved delete requests',
    'deleteRequests.noRejectedRequests': 'No rejected delete requests',
    'deleteRequests.approveFailed': 'Failed to approve request',
    'deleteRequests.rejectFailed': 'Failed to reject request',
    'deleteRequests.rejectRequest': 'Reject Delete Request',
    'deleteRequests.rejectionReasonRequired': 'Rejection reason is required',
    'deleteRequests.rejectionReasonPlaceholder': 'Please provide a reason for rejection...',
    'deleteRequests.rejectionReasonHelp': 'This reason will be visible to the requester',
    'deleteRequests.rejecting': 'Rejecting...',
    'deleteRequests.approveRequest': 'Approve Delete Request',
    'deleteRequests.approvalReason': 'Approval Reason',
    'deleteRequests.approvalReasonPlaceholder': 'Optional: Add a comment or reason for approval...',
    'deleteRequests.approvalReasonHelp': 'This comment will be visible to the requester',
    'deleteRequests.approving': 'Approving...',
    'deleteRequests.optional': 'optional',
    'deleteRequests.requests': 'requests',

    // Permission Errors
    'error.permissionDenied': 'Permission Denied',
    'error.onlyAdminCanDelete': 'Only Admins can delete customers directly',
    'error.officerMustRequestDelete': 'Officers must request customer deletion from Admin',
    'error.customerAgentReadOnly': 'Business Managers have read-only access',
    'error.onlyAdminOfficerCanEdit': 'Only Admins and Officers can edit customers',
    'error.onlyAdminOfficerCanAdd': 'Only Admins and Officers can add customers',

    // Registration Success
    'register.success.title': 'Registration Successful!',
    'register.success.message': 'Your account has been created and is pending approval.',
    'register.success.adminReview': 'An administrator will review your request shortly.',
    'register.success.notification': 'You will be notified once your account is approved.',
    'register.success.backToLogin': 'Back to Login',

    // Validation messages
    'validation.phoneRequired': 'Phone number is required',
    'validation.nameRequired': 'Name is required',
    'validation.invalidPhone': 'Please enter a valid phone number',
    'validation.phoneLength': 'Phone number must be 11 digits',
    'validation.nameLength': 'Name must be 2-50 characters',
    'validation.ageInvalid': 'Please enter a valid age between 1 and 120',

    // Common actions
    'actions.save': 'Save',
    'actions.cancel': 'Cancel',
    'actions.delete': 'Delete',
    'actions.edit': 'Edit',
    'actions.add': 'Add',
    'actions.create': 'Create',
    'actions.update': 'Update',
    'actions.back': 'Back',
    'actions.next': 'Next',
    'actions.previous': 'Previous',
    'actions.close': 'Close',
    'actions.confirm': 'Confirm',
    'actions.submit': 'Submit',
    'actions.reset': 'Reset',
    'actions.clear': 'Clear',
    'actions.view': 'View',
    'actions.details': 'Details',
    'actions.approve': 'Approve',
    'actions.reject': 'Reject',
    'actions.loading': 'Loading...',

    // Dashboard - Admin
    'dashboard.admin.title': 'Admin Dashboard',
    'dashboard.admin.subtitle': 'System-wide analytics and insights',
    'dashboard.admin.overview': 'Overview',
    'dashboard.admin.salesLeaderboard': 'Sales Leaderboard',
    'dashboard.admin.systemHealth': 'System Health',
    'dashboard.admin.analytics': 'Analytics',
    'dashboard.admin.backToCustomers': 'Back to Customers',

    // Dashboard - Sales
    'dashboard.sales.title': 'Business Manager Dashboard',
    'dashboard.sales.subtitle': 'Your personal performance metrics',
    'dashboard.sales.myPerformance': 'My Performance',
    'dashboard.sales.pipeline': 'Pipeline',
    'dashboard.sales.targets': 'Targets',

    // Dashboard - Metrics
    'dashboard.metrics.totalCustomers': 'Total Customers',
    'dashboard.metrics.newCustomers': 'New Customers',
    'dashboard.metrics.activeCustomers': 'Active Customers',
    'dashboard.metrics.conversionRate': 'Conversion Rate',
    'dashboard.metrics.thisMonth': 'This Month',
    'dashboard.metrics.lastMonth': 'Last Month',
    'dashboard.metrics.change': 'change',
    'dashboard.metrics.vs': 'vs',
    'dashboard.metrics.period': 'period',
    'dashboard.metrics.newCustomers30d': 'New Customers (30d)',
    'dashboard.metrics.fromLastPeriod': 'from last period',
    'dashboard.metrics.recentActivity': 'Recent activity in last 30 days',
    'dashboard.metrics.loadingDashboard': 'Loading dashboard...',
    'dashboard.metrics.errorLoadingDashboard': 'Error loading dashboard',
    'dashboard.metrics.viewCustomers': 'View Customers',
    'dashboard.metrics.salesPerformance': 'Sales Performance',
    'dashboard.metrics.myCustomers': 'My Customers',
    'dashboard.metrics.myConversions': 'My Conversions',
    'dashboard.metrics.myConversionRate': 'My Conversion Rate',

    // Dashboard - Charts
    'dashboard.charts.statusDistribution': 'Customer Status Distribution',
    'dashboard.charts.trends': 'Customer Growth Trends',
    'dashboard.charts.performance': 'Performance Analytics',
    'dashboard.charts.noData': 'No data available',
    'dashboard.charts.loading': 'Loading chart data...',
    'dashboard.charts.error': 'Error',
    'dashboard.charts.errorLoading': 'Error loading chart',
    'dashboard.charts.total': 'total',
    'dashboard.charts.totalCustomers': 'Total Customers',
    'dashboard.charts.customers': 'customers',
    'dashboard.charts.ofTotal': 'of total',
    'dashboard.charts.quickStats': 'Quick Stats',
    'dashboard.charts.highestCount': 'Highest Count',
    'dashboard.charts.statusTypes': 'Status Types',
    'dashboard.charts.dataWillAppear': 'Customer status data will appear here when available',
    'dashboard.charts.newCustomers': 'New Customers',
    'dashboard.charts.conversionRate': 'Conversion Rate (%)',
    'dashboard.charts.leaderboard': 'Sales Team Leaderboard',
    'dashboard.charts.myPipeline': 'My Pipeline Status',
    'dashboard.charts.performanceSummary': 'Performance Summary',
    'dashboard.charts.quickActions': 'Quick Actions',
    'dashboard.charts.viewMode': 'View Mode',
    'dashboard.charts.all': 'All',
    'dashboard.charts.daily': 'Daily',
    'dashboard.charts.weekly': 'Weekly',
    'dashboard.charts.monthly': 'Monthly',
    'dashboard.charts.view': 'View:',
    'dashboard.charts.latestNew': 'Latest New',
    'dashboard.charts.totalNow': 'Total Now',

    // User Approvals
    'approvals.title': 'User Approvals',
    'approvals.subtitle': 'Review and approve user registration requests',
    'approvals.pending': 'Pending Approvals',
    'approvals.approved': 'Approved Users',
    'approvals.rejected': 'Rejected Users',
    'approvals.all': 'All Users',
    'approvals.phone': 'Phone Number',
    'approvals.status': 'Status',
    'approvals.requestDate': 'Request Date',
    'approvals.approvedDate': 'Approved Date',
    'approvals.rejectedDate': 'Rejected Date',
    'approvals.actions': 'Actions',
    'approvals.noRequests': 'No approval requests found',
    'approvals.loadingRequests': 'Loading approval requests...',
    'approvals.errorLoading': 'Error loading approval requests',
    'approvals.confirmApprove': 'Are you sure you want to approve this user?',
    'approvals.confirmReject': 'Are you sure you want to reject this user?',
    'approvals.approveSuccess': 'User approved successfully',
    'approvals.rejectSuccess': 'User rejected successfully',
    'approvals.approveFailed': 'Failed to approve user',
    'approvals.rejectFailed': 'Failed to reject user',
    'approvals.daysWaiting': 'Days Waiting',
    'approvals.days': 'days',
    'approvals.rejectionReason': 'Reason',
    'approvals.reasonRequired': '* Reason is required',

    // User Management
    'userManagement.title': 'User Management',
    'userManagement.subtitle': 'Manage user accounts and permissions',
    'userManagement.accountStatus': 'Account Status',
    'userManagement.enabled': 'Enabled',
    'userManagement.disabled': 'Disabled',
    'userManagement.enableUser': 'Enable User',
    'userManagement.disableUser': 'Disable User',
    'userManagement.enableTitle': 'Enable User Account',
    'userManagement.enableDescription': 'Enable account for',
    'userManagement.enableButton': 'Enable Account',
    'userManagement.enableReason': 'Enable reason (optional)',
    'userManagement.enablePlaceholder': 'e.g., Account reactivated after review...',
    'userManagement.disableTitle': 'Disable User Account',
    'userManagement.disableDescription': 'Disable account for',
    'userManagement.disableButton': 'Disable Account',
    'userManagement.disableReason': 'Disable reason *',
    'userManagement.disablePlaceholder': 'e.g., Temporary suspension, policy violation...',
    'userManagement.allUsers': 'All Users',
    'userManagement.userApprovals': 'User Approvals',
    'userManagement.allUsersDescription': 'View and manage all user accounts',
    'userManagement.active': 'ACTIVE',

    // Customer Detail
    'detail.customerDetails': 'Customer Details',
    'detail.overview': 'Overview',
    'detail.statusHistory': 'Status History',
    'detail.personalInfo': 'Personal Information',
    'detail.businessInfo': 'Business Information',
    'detail.contactInfo': 'Contact Information',
    'detail.systemInfo': 'System Information',
    'detail.createdBy': 'Created by',
    'detail.createdAt': 'Created at',
    'detail.updatedAt': 'Last updated',
    'detail.currentStatus': 'Current Status',
    'detail.statusChanges': 'Status Changes',
    'detail.changeHistory': 'Change History',
    'detail.changedBy': 'Changed by',
    'detail.changedAt': 'Changed at',
    'detail.fromStatus': 'From',
    'detail.toStatus': 'To',
    'detail.noHistory': 'No status history available',
    'detail.loadingHistory': 'Loading status history...',
    'detail.errorHistory': 'Error loading status history'
  },
  'zh-CN': {
    // Common
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.save': '保存',
    'common.close': '关闭',
    'common.loading': '加载中...',
    'common.search': '搜索',
    'common.searching': '搜索中...',


    // Settings
    'settings.title': '设置',
    'settings.language': '语言',
    'settings.language.en': 'English',
    'settings.language.zh-CN': '简体中文',

    // Map Picker
    'map.selectLocation': '选择位置',
    'map.searchPlaceholder': '搜索位置...',
    'map.myLocation': '我的位置',
    'map.locating': '定位中...',
    'map.selectedLocation': '选中位置',
    'map.noLocationSelected': '未选择位置',
    'map.clickToSelect': '点击地图或搜索位置',
    'map.confirmSelection': '确认选择',
    'map.gettingAddress': '正在获取地址...',
    'map.currentLocation': '当前位置',
    'map.location': '位置',
    'map.unknown': '未知',
    'map.china': '中国',
    'map.howToUse': '使用说明：',
    'map.howToUse1': '我的位置 - 自动定位到当前位置',
    'map.howToUse2': '搜索位置',
    'map.howToUse3': '点击地图选择位置',
    'map.howToUse4': '查看详情并确认',
    'map.loadingMap': '加载地图中...',
    'map.locationAccessDenied': '用户拒绝了位置访问请求，请在浏览器设置中允许位置访问',
    'map.locationUnavailable': '位置信息不可用，请检查GPS或网络连接',
    'map.locationTimeout': '位置请求超时，请重试',
    'map.locationError': '获取位置时发生错误',
    'map.yourLocation': '您的位置：',

    // Customer Management
    'customer.addCustomer': '添加客户',
    'customer.editCustomer': '编辑客户',
    'customer.deleteCustomer': '删除客户',
    'customer.restoreCustomer': '恢复客户',
    'customer.customerDetails': '客户详情',
    'customer.statusHistory': '状态历史',
    'customer.name': '姓名',
    'customer.phone': '电话',
    'customer.certificateIssuer': '发证机关',
    'customer.businessRequirements': '备注',
    'customer.certificateType': '证书类型',
    'customer.age': '年龄',
    'customer.education': '教育程度',
    'customer.gender': '性别',
    'customer.location': '位置',
    'customer.price': '价格',
    'customer.currentStatus': '当前状态',
    'customer.salesPerson': '业务经理',
    'customer.customerAgent': '业务经理',
    'customer.createdAt': '创建时间',
    'customer.updatedAt': '更新时间',

    // Status
    'status.new': '新用户',
    'status.notified': '已提醒复审',
    'status.aborted': '客户放弃',
    'status.submitted': '已提交资料',
    'status.certified': '已发证',

    // Approval Status
    'approvalStatus.pending': '待审批',
    'approvalStatus.approved': '已批准',
    'approvalStatus.rejected': '已拒绝',

    // Dashboard
    'dashboard.title': '仪表板',
    'dashboard.totalCustomers': '总客户数',
    'dashboard.newCustomers': '新客户',
    'dashboard.activeCustomers': '活跃客户',
    'dashboard.conversionRate': '转化率',
    'dashboard.salesLeaderboard': '业务经理排行榜',
    'dashboard.performance': '绩效',
    'dashboard.metrics': '指标',

    // Auth
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.logout': '退出登录',
    'auth.phone': '电话',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.loginSuccess': '登录成功',
    'auth.registerSuccess': '注册成功',
    'auth.loginFailed': '登录失败',
    'auth.registerFailed': '注册失败',
    'auth.welcomeBack': '欢迎回来',
    'auth.signInToAccount': '登录到您的业务经理账户',
    'auth.phoneNumber': '手机号码',
    'auth.enterPhone': '请输入您的手机号码',
    'auth.enterPassword': '请输入您的密码',
    'auth.signingIn': '登录中...',
    'auth.signIn': '登录',
    'auth.dontHaveAccount': '还没有账户？',
    'auth.createAccount': '创建账户',
    'auth.registrationComplete': '注册完成！',
    'auth.customerTracker': '客户跟踪系统',

    // Error messages
    'error.phonePasswordRequired': '手机号码和密码为必填项',
    'error.incorrectCredentials': '手机号码或密码错误。请检查您的凭据并重试。',
    'error.networkError': '无法连接到服务器。请检查您的网络连接并重试。',
    'error.unexpectedError': '发生意外错误。请重试。',
    'error.loginFailed': '登录失败',
    'error.invalidCredentials': '凭据无效',
    'error.accountPending': '账户等待审批',
    'error.accountDenied': '账户访问被拒绝',
    'error.accountDisabled': '您的账户已被管理员禁用。请联系技术支持获取帮助。',
    'error.connectionError': '连接错误',
    'error.dismissMessage': '关闭错误消息',
    'error.phoneAlreadyExists': '手机号码已存在',
    'error.invalidToken': '无效或过期的令牌',
    'error.invalidResponse': '服务器响应无效',

    // Error help messages
    'error.tips': '提示：',
    'error.checkPhoneFormat': '请仔细检查您的手机号码格式',
    'error.ensurePassword': '确保您的密码正确',
    'error.capsLock': '确保未启用大写锁定',
    'error.whatToDo': '下一步操作：',
    'error.waitApproval': '请等待管理员审批',
    'error.contactAdmin': '如需立即访问请联系管理员',
    'error.tryAgainLater': '稍后再次尝试登录',
    'error.needHelp': '需要帮助？',
    'error.contactSystemAdmin': '联系系统管理员讨论您的账户状态并请求访问权限。',
    'error.trySteps': '尝试以下步骤：',
    'error.checkConnection': '检查您的网络连接',
    'error.refreshPage': '刷新页面并重试',
    'error.contactSupport': '如果问题持续存在，请联系技术支持',

    // Navigation
    'nav.dashboard': '仪表板',
    'nav.customers': '客户',
    'nav.settings': '设置',
    'nav.userApprovals': '用户审批',
    'nav.userManagement': '用户管理',
    'nav.refresh': '刷新',
    'nav.refreshing': '刷新中...',

    // General
    'general.admin': '管理员',

    // App
    'app.customerTracker': '客户跟踪系统',
    'app.professionalCRM': '专业客户关系管理解决方案',
    'app.admin': '（管理员）',

    // Customer List
    'customers.management': '客户管理',
    'customers.manageTrack': '管理和跟踪客户关系',
    'customers.addCustomer': '添加客户',
    'customers.searchFilter': '搜索和筛选',
    'customers.searchPlaceholder': '按姓名或电话搜索...',
    'customers.search': '搜索',
    'customers.searchStatus': '状态',
    'customers.allStatuses': '所有状态',
    'customers.clearFilters': '清除',
    'customers.certifiedTimeRange': '取证时间范围',
    'customers.startDate': '开始日期',
    'customers.endDate': '结束日期',
    'customers.clear': '清除',
    'customers.errorLoading': '加载客户时出错',
    'customers.tryAgain': '重试',
    'customers.loadingCustomers': '正在加载客户...',
    'customers.noCustomersFound': '未找到客户',
    'customers.adjustSearch': '请调整搜索条件',
    'customers.getStartedFirst': '开始添加您的第一个客户',
    'customers.clearSearch': '清除搜索',
    'customers.customersFound': '个客户',
    'customers.customersFoundPlural': '个客户',
    'customers.found': '找到',
    'customers.page': '第',
    'customers.of': '页，共',
    'customers.pageInfo': '第 {page} 页，共 {total} 页',
    'customers.showing': '显示',
    'customers.to': '到',
    'customers.customers': '个客户',
    'customers.show': '显示：',
    'customers.perPage': '每页',
    'customers.previous': '上一页',
    'customers.next': '下一页',
    'customers.name': '姓名',
    'customers.phone': '电话',
    'customers.cancel': '取消',
    'customers.ok': '确定',
    'customers.detail.customer': '客户',

    // Customer Form
    'customers.form.createCustomer': '创建客户',
    'customers.form.editCustomer': '编辑客户',
    'customers.form.customerInfo': '客户信息',
    'customers.form.name': '姓名',
    'customers.form.phone': '手机号码',
    'customers.form.certificateIssuer': '发证机关',
    'customers.form.certificateIssuer.placeholder': '输入发证机关',
    'customers.form.businessReq': '备注',
    'customers.form.businessType': '证书类型',
    'customers.form.certificateType': '证书类型',
    'customers.form.age': '年龄',
    'customers.form.education': '教育程度',
    'customers.form.gender': '性别',
    'customers.form.gender.male': '男',
    'customers.form.gender.female': '女',
    'customers.form.gender.other': '其他',
    'customers.form.gender.select': '选择性别',
    'customers.form.location': '位置',
    'customers.form.salesPerson': '添加人',
    'customers.form.salesPerson.unknown': '未知',
    'customers.form.salesPerson.you': '您',
    'customers.form.salesPerson.admin': '管理员',
    'customers.form.salesPerson.officer': '文员',
    'customers.form.salesPerson.customerAgent': '业务经理',
    'customers.form.customerAgent': '业务经理',
    'customers.form.customerAgent.placeholder': '输入经理名字',
    'customers.detail.statusManagement': '状态管理',
    'customers.detail.updateStatus': '更新状态',
    'customers.detail.updating': '更新中...',
    'detail.initialStatus': '初始状态：',
    'customers.detail.businessComplete': '业务流程已完成 - 不允许进一步转换',
    'customers.detail.loadingTransitions': '正在加载可用转换...',
    'customers.detail.initialCreation': '初始创建客户',
    'customers.detail.statusReason': '输入状态变更原因...',
    'customers.detail.reasonOptional': '原因（可选）',
    'customers.detail.newStatus': '新状态',
    'customers.detail.noTransitionsAvailable': '无可用状态转换',
    'customers.detail.selectEducationLevel': '选择教育水平',
    'customers.detail.notSpecified': '未指定',

    // Education Levels
    'education.elementary': '小学',
    'education.middleSchool': '初中',
    'education.highSchool': '高中',
    'education.associate': '大专',
    'education.bachelor': '学士学位',
    'education.master': '硕士学位',
    'education.doctorate': '博士学位',
    'education.professional': '专业学位',
    'education.certificate': '证书/文凭',
    'education.other': '其他',
    'certificateType.electrician': '电工',
    'certificateType.welder': '焊工',
    'certificateType.excavator': '挖掘机',
    'customers.form.selectCertificateType': '选择证书类型',
    'approvals.showing': '显示',
    'approvals.to': '到',
    'approvals.of': '共',
    'approvals.users': '个用户',
    'approvals.show': '显示：',
    'approvals.perPage': '每页',
    'approvals.noUsersFound': '未找到用户',
    'approvals.noUsersFoundMatching': '未找到匹配的用户',
    'approvals.noUsersWithStatus': '未找到状态为',
    'approvals.approveUser': '批准用户',
    'approvals.rejectUser': '拒绝用户',
    'approvals.resetToPending': '重置为待审批',
    'approvals.firstPage': '第一页',
    'approvals.previousPage': '上一页',
    'approvals.nextPage': '下一页',
    'approvals.lastPage': '最后一页',
    'approvals.approveTitle': '批准用户注册',
    'approvals.approveDescription': '批准注册',
    'approvals.approveButton': '批准用户',
    'approvals.approveReason': '批准原因（可选）',
    'approvals.approvePlaceholder': '例如：申请看起来不错，已验证身份...',
    'approvals.rejectTitle': '拒绝用户注册',
    'approvals.rejectDescription': '拒绝注册',
    'approvals.rejectButton': '拒绝用户',
    'approvals.rejectReason': '拒绝原因 *',
    'approvals.rejectPlaceholder': '例如：申请不完整，验证失败...',
    'approvals.rejectRequired': '* 拒绝原因是必填的',
    'approvals.resetTitle': '重置用户状态',
    'approvals.resetDescription': '重置',
    'approvals.resetDescription2': '状态为待审批？',
    'approvals.resetButton': '重置状态',
    'approvals.resetReason': '重置原因（可选）',
    'approvals.resetPlaceholder': '例如：需要重新审核申请...',
    'approvals.processing': '处理中...',
    'dashboard.sales.myConversionRate': '我的转化率',
    'dashboard.sales.conversionProgress': '转化进度',
    'dashboard.sales.conversionRate': '转化率',
    'dashboard.sales.keyMetrics': '关键指标',
    'dashboard.sales.newCustomers': '新客户',
    'dashboard.sales.conversions': '转化',
    'dashboard.sales.rate': '率',
    'dashboard.sales.quickActions': '快速操作',
    'dashboard.sales.viewAllCustomers': '查看所有客户',
    'dashboard.sales.followUpCalls': '跟进电话',
    'dashboard.sales.pendingOrders': '待处理订单',
    'customers.form.price': '价格',
    'customers.form.certifiedAt': '取证日期',
    'customers.form.certifiedAt.placeholder': '选择取证日期',
    'customers.form.status': '初始状态',
    'customers.form.selectLocation': '选择位置',
    'customers.form.creating': '创建中...',
    'customers.form.create': '创建客户',
    'customers.form.updating': '更新中...',
    'customers.form.update': '更新客户',
    'customers.form.cancel': '取消',
    'customers.form.customerCreated': '客户创建成功！',
    'customers.form.customerUpdated': '客户更新成功！',
    'customers.form.failedCreate': '创建客户失败',
    'customers.form.failedUpdate': '更新客户失败',
    'customers.form.requiredFields': '请填写所有必填字段',

    // Customer Detail
    'customers.detail.customerDetails': '客户详情',
    'customers.detail.statusHistory': '状态历史',
    'customers.detail.personalInfo': '个人信息',
    'customers.detail.businessInfo': '业务信息',
    'customers.detail.contactInfo': '联系信息',
    'customers.detail.edit': '编辑',
    'customers.detail.delete': '删除',
    'customers.detail.restore': '恢复',
    'customers.detail.back': '返回列表',
    'customers.detail.loading': '正在加载客户详情...',
    'customers.detail.notFound': '客户未找到',
    'customers.detail.failedLoad': '加载客户详情失败',
    'customers.detail.confirmDelete': '确定要删除这个客户吗？',
    'customers.detail.confirmRestore': '确定要恢复这个客户吗？',
    'customers.detail.deleteSuccess': '客户删除成功',
    'customers.detail.restoreSuccess': '客户恢复成功',

    // Registration
    'register.createAccount': '创建账户',
    'register.joinPlatform': '加入我们的客户管理平台',
    'register.allFieldsRequired': '所有字段都是必填的',
    'register.passwordsDontMatch': '密码不匹配',
    'register.passwordTooShort': '密码至少需要6个字符',
    'register.confirmPassword': '确认密码',
    'register.enterConfirmPassword': '确认您的密码',
    'register.creating': '创建账户中...',
    'register.alreadyHaveAccount': '已有账户？',
    'register.signIn': '登录',
    'register.createPassword': '创建密码',
    'register.minimumChars': '至少6个字符',
    'register.selectRole': '选择角色',
    'register.role': '角色',

    // Roles
    'role.admin': '管理员',
    'role.officer': '文员',
    'role.customerAgent': '业务经理',

    // Delete Requests
    'deleteRequests.title': '客户删除请求',
    'deleteRequests.subtitle': '审查和管理客户删除请求',
    'deleteRequests.noRequests': '没有待处理的删除请求',
    'deleteRequests.loadingRequests': '加载删除请求中...',
    'deleteRequests.requestedBy': '请求人',
    'deleteRequests.customer': '客户',
    'deleteRequests.reason': '原因',
    'deleteRequests.requestedAt': '请求时间',
    'deleteRequests.status': '状态',
    'deleteRequests.actions': '操作',
    'deleteRequests.approve': '批准',
    'deleteRequests.reject': '拒绝',
    'deleteRequests.approveSuccess': '删除请求已批准',
    'deleteRequests.rejectSuccess': '删除请求已拒绝',
    'deleteRequests.confirmApprove': '确定要批准此请求吗？这将删除该客户。',
    'deleteRequests.confirmReject': '确定要拒绝此请求吗？',
    'deleteRequests.requestDeletion': '请求删除',
    'deleteRequests.requestDeleteSuccess': '删除请求提交成功',
    'deleteRequests.requestDeleteError': '提交删除请求失败',
    'deleteRequests.pendingRequestExists': '该客户已有一个待处理的删除请求',
    'deleteRequests.requestSubmitted': '请求已提交',
    'deleteRequests.reasonRequired': '原因为必填项',
    'deleteRequests.reasonPlaceholder': '请提供删除请求的原因...',
    'deleteRequests.submitting': '提交中...',
    'deleteRequests.pending': '待处理',
    'deleteRequests.approved': '已批准',
    'deleteRequests.rejected': '已拒绝',
    'deleteRequests.rejectionReason': '拒绝原因',
    'deleteRequests.all': '全部',
    'deleteRequests.pendingRequests': '待处理的删除请求',
    'deleteRequests.pendingRequestsDescription': '审查并批准或拒绝客户删除请求',
    'deleteRequests.searchPlaceholder': '按姓名、电话或请求人搜索',
    'deleteRequests.noRequestsFound': '未找到删除请求',
    'deleteRequests.noRequestsMatching': '未找到匹配的删除请求',
    'deleteRequests.noPendingRequests': '没有待处理的删除请求',
    'deleteRequests.noApprovedRequests': '没有已批准的删除请求',
    'deleteRequests.noRejectedRequests': '没有已拒绝的删除请求',
    'deleteRequests.approveFailed': '批准请求失败',
    'deleteRequests.rejectFailed': '拒绝请求失败',
    'deleteRequests.rejectRequest': '拒绝删除请求',
    'deleteRequests.rejectionReasonRequired': '拒绝原因为必填项',
    'deleteRequests.rejectionReasonPlaceholder': '请提供拒绝原因...',
    'deleteRequests.rejectionReasonHelp': '该原因将对请求人可见',
    'deleteRequests.rejecting': '拒绝中...',
    'deleteRequests.approveRequest': '批准删除请求',
    'deleteRequests.approvalReason': '批准原因',
    'deleteRequests.approvalReasonPlaceholder': '可选：添加批准意见或原因...',
    'deleteRequests.approvalReasonHelp': '该意见将对请求人可见',
    'deleteRequests.approving': '批准中...',
    'deleteRequests.optional': '可选',
    'deleteRequests.requests': '个请求',

    // Permission Errors
    'error.permissionDenied': '权限不足',
    'error.onlyAdminCanDelete': '只有管理员可以直接删除客户',
    'error.officerMustRequestDelete': '文员必须向管理员请求删除客户',
    'error.customerAgentReadOnly': '业务经理只有只读权限',
    'error.onlyAdminOfficerCanEdit': '只有管理员和文员可以编辑客户',
    'error.onlyAdminOfficerCanAdd': '只有管理员和文员可以添加客户',

    // Registration Success
    'register.success.title': '注册成功！',
    'register.success.message': '您的账户已创建，正在等待审批。',
    'register.success.adminReview': '管理员将很快审核您的请求。',
    'register.success.notification': '账户获得批准后将通知您。',
    'register.success.backToLogin': '返回登录',

    // Validation messages
    'validation.phoneRequired': '手机号码为必填项',
    'validation.nameRequired': '姓名为必填项',
    'validation.invalidPhone': '请输入有效的手机号码',
    'validation.phoneLength': '手机号码必须是11位数字',
    'validation.nameLength': '姓名长度必须为2-50个字符',
    'validation.ageInvalid': '请输入1-120之间的有效年龄',

    // Common actions
    'actions.save': '保存',
    'actions.cancel': '取消',
    'actions.delete': '删除',
    'actions.edit': '编辑',
    'actions.add': '添加',
    'actions.create': '创建',
    'actions.update': '更新',
    'actions.back': '返回',
    'actions.next': '下一步',
    'actions.previous': '上一步',
    'actions.close': '关闭',
    'actions.confirm': '确认',
    'actions.submit': '提交',
    'actions.reset': '重置',
    'actions.clear': '清除',
    'actions.view': '查看',
    'actions.details': '详情',
    'actions.approve': '批准',
    'actions.reject': '拒绝',
    'actions.loading': '加载中...',

    // Dashboard - Admin
    'dashboard.admin.title': '管理员仪表板',
    'dashboard.admin.subtitle': '系统范围的分析和洞察',
    'dashboard.admin.overview': '概览',
    'dashboard.admin.salesLeaderboard': '业务经理排行榜',
    'dashboard.admin.systemHealth': '系统健康状况',
    'dashboard.admin.analytics': '分析',
    'dashboard.admin.backToCustomers': '返回客户',

    // Dashboard - Sales
    'dashboard.sales.title': '业务经理仪表板',
    'dashboard.sales.subtitle': '您的个人绩效指标',
    'dashboard.sales.myPerformance': '我的绩效',
    'dashboard.sales.pipeline': '销售漏斗',
    'dashboard.sales.targets': '目标',

    // Dashboard - Metrics
    'dashboard.metrics.totalCustomers': '总客户数',
    'dashboard.metrics.newCustomers': '新客户',
    'dashboard.metrics.activeCustomers': '活跃客户',
    'dashboard.metrics.conversionRate': '转化率',
    'dashboard.metrics.thisMonth': '本月',
    'dashboard.metrics.lastMonth': '上月',
    'dashboard.metrics.change': '变化',
    'dashboard.metrics.vs': '对比',
    'dashboard.metrics.period': '期间',
    'dashboard.metrics.newCustomers30d': '新客户（30天）',
    'dashboard.metrics.fromLastPeriod': '对比上期',
    'dashboard.metrics.recentActivity': '最近30天活跃度',
    'dashboard.metrics.loadingDashboard': '正在加载仪表板...',
    'dashboard.metrics.errorLoadingDashboard': '加载仪表板时出错',
    'dashboard.metrics.viewCustomers': '查看客户',
    'dashboard.metrics.salesPerformance': '业务经理绩效',
    'dashboard.metrics.myCustomers': '我的客户',
    'dashboard.metrics.myConversions': '我的转化',
    'dashboard.metrics.myConversionRate': '我的转化率',

    // Dashboard - Charts
    'dashboard.charts.statusDistribution': '客户状态分布',
    'dashboard.charts.trends': '客户增长趋势',
    'dashboard.charts.performance': '绩效分析',
    'dashboard.charts.noData': '暂无数据',
    'dashboard.charts.loading': '正在加载图表数据...',
    'dashboard.charts.error': '错误',
    'dashboard.charts.errorLoading': '图表加载出错',
    'dashboard.charts.total': '总计',
    'dashboard.charts.totalCustomers': '客户总数',
    'dashboard.charts.customers': '客户',
    'dashboard.charts.ofTotal': '占总数',
    'dashboard.charts.quickStats': '快速统计',
    'dashboard.charts.highestCount': '最高数量',
    'dashboard.charts.statusTypes': '状态类型',
    'dashboard.charts.dataWillAppear': '客户状态数据可用时将显示在此处',
    'dashboard.charts.newCustomers': '新客户',
    'dashboard.charts.conversionRate': '转化率 (%)',
    'dashboard.charts.leaderboard': '业务经理团队排行榜',
    'dashboard.charts.myPipeline': '我的管道状态',
    'dashboard.charts.performanceSummary': '绩效摘要',
    'dashboard.charts.quickActions': '快速操作',
    'dashboard.charts.viewMode': '查看模式',
    'dashboard.charts.all': '全部',
    'dashboard.charts.daily': '每日',
    'dashboard.charts.weekly': '每周',
    'dashboard.charts.monthly': '每月',
    'dashboard.charts.view': '查看：',
    'dashboard.charts.latestNew': '最新新增',
    'dashboard.charts.totalNow': '当前总数',

    // User Approvals
    'approvals.title': '用户审批',
    'approvals.subtitle': '审核和批准用户注册请求',
    'approvals.pending': '待审批',
    'approvals.approved': '已批准用户',
    'approvals.rejected': '已拒绝用户',
    'approvals.all': '所有用户',
    'approvals.phone': '手机号码',
    'approvals.status': '状态',
    'approvals.requestDate': '请求日期',
    'approvals.approvedDate': '批准日期',
    'approvals.rejectedDate': '拒绝日期',
    'approvals.actions': '操作',
    'approvals.noRequests': '未找到审批请求',
    'approvals.loadingRequests': '正在加载审批请求...',
    'approvals.errorLoading': '加载审批请求时出错',
    'approvals.confirmApprove': '确定要批准这个用户吗？',
    'approvals.confirmReject': '确定要拒绝这个用户吗？',
    'approvals.approveSuccess': '用户批准成功',
    'approvals.rejectSuccess': '用户拒绝成功',
    'approvals.approveFailed': '批准用户失败',
    'approvals.rejectFailed': '拒绝用户失败',
    'approvals.daysWaiting': '等待天数',
    'approvals.days': '天',
    'approvals.rejectionReason': '原因',
    'approvals.reasonRequired': '* 原因是必填的',

    // User Management
    'userManagement.title': '用户管理',
    'userManagement.subtitle': '管理用户账户和权限',
    'userManagement.accountStatus': '账户状态',
    'userManagement.enabled': '已启用',
    'userManagement.disabled': '已禁用',
    'userManagement.enableUser': '启用用户',
    'userManagement.disableUser': '禁用用户',
    'userManagement.enableTitle': '启用用户账户',
    'userManagement.enableDescription': '启用账户',
    'userManagement.enableButton': '启用账户',
    'userManagement.enableReason': '启用原因（可选）',
    'userManagement.enablePlaceholder': '例如：审核后重新激活账户...',
    'userManagement.disableTitle': '禁用用户账户',
    'userManagement.disableDescription': '禁用账户',
    'userManagement.disableButton': '禁用账户',
    'userManagement.disableReason': '禁用原因 *',
    'userManagement.disablePlaceholder': '例如：临时暂停，违反政策...',
    'userManagement.allUsers': '所有用户',
    'userManagement.userApprovals': '用户审批',
    'userManagement.allUsersDescription': '查看和管理所有用户账户',
    'userManagement.active': '活跃',

    // Customer Detail
    'detail.customerDetails': '客户详情',
    'detail.overview': '概览',
    'detail.statusHistory': '状态历史',
    'detail.personalInfo': '个人信息',
    'detail.businessInfo': '业务信息',
    'detail.contactInfo': '联系信息',
    'detail.systemInfo': '系统信息',
    'detail.createdBy': '创建者',
    'detail.createdAt': '创建时间',
    'detail.updatedAt': '最后更新',
    'detail.currentStatus': '当前状态',
    'detail.statusChanges': '状态变化',
    'detail.changeHistory': '变更历史',
    'detail.changedBy': '变更者',
    'detail.changedAt': '变更时间',
    'detail.fromStatus': '从',
    'detail.toStatus': '到',
    'detail.noHistory': '暂无状态历史',
    'detail.loadingHistory': '正在加载状态历史...',
    'detail.errorHistory': '加载状态历史时出错'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh-CN')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  // Translation function with parameter support
  const t = (key: string, params?: Record<string, string | number>): string => {
    const languageTranslations = translations[language];
    let translation = languageTranslations[key as keyof typeof languageTranslations] || key;

    // Replace parameters in the translation string
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, String(params[param]));
      });
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
